import React,{useEffect,useState} from "react";
import {getCurrentUser,requestPasswordReset,signIn,signUp,updatePassword} from "./api.js";
import {Brand,Button,go} from "./ui-v4.jsx";

export default function LoginPage(){
  const [user,setUser]=useState(undefined),[mode,setMode]=useState("login"),[role,setRole]=useState("parent"),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[name,setName]=useState(""),[childName,setChildName]=useState(""),[ageBand,setAgeBand]=useState("7-9"),[ageYears,setAgeYears]=useState(8),[gender,setGender]=useState("unspecified"),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[error,setError]=useState("");
  useEffect(()=>{let alive=true;(async()=>{try{const current=await getCurrentUser();if(!alive)return;setUser(current);if(current)setMode("update");}catch(e){if(alive){setUser(null);setError(e.message||"تعذر التحقق من الحساب.");}}})();return()=>{alive=false;};},[]);
  function changeMode(next){setMode(next);setMessage("");setError("");setPassword("");}
  async function submit(e){e.preventDefault();setBusy(true);setMessage("");setError("");try{if(mode==="login"){const current=await signIn(email,password);setUser(current);go(current.accountType==="teacher"?"/teacher":"/family");}else if(mode==="signup"){const result=await signUp({email,password,displayName:name,accountType:role,childName,childAgeBand:ageBand,childAgeYears:Number(ageYears),childGender:gender});if(result.sessionCreated){const current=await getCurrentUser();setUser(current);go(role==="teacher"?"/teacher":"/family");}else{setMessage("تم إنشاء الحساب. تحقق من بريدك ثم سجل الدخول.");changeMode("login");}}else if(mode==="recover"){await requestPasswordReset(email);setMessage("أرسلنا رابط استعادة كلمة المرور إلى بريدك المسجل.");}else{await updatePassword(password);setMessage("تم تغيير كلمة المرور بنجاح.");setUser(await getCurrentUser());}}catch(e){setError(e.message||"تعذر تنفيذ الطلب.");}finally{setBusy(false);}}
  if(user===undefined)return <div className="center"><i className="spinner"/><p>جارٍ تجهيز الحساب...</p></div>;
  const heading=mode==="login"?"أهلًا بعودتك":mode==="signup"?"ابدأ رحلة التعلم":mode==="recover"?"استعادة كلمة المرور":"اختَر كلمة مرور جديدة";
  const description=mode==="login"?"ادخل إلى حساب الأسرة أو لوحة المعلم وتابع من آخر نقطة.":mode==="signup"?"حساب واحد للأسرة أو المعلم، وبعده نرتب رحلة الطفل ببساطة.":mode==="recover"?"سنرسل رابط الاستعادة إلى بريدك المسجل.":"اكتب كلمة مرور جديدة ثم ارجع إلى حسابك.";
  const assetBase=window.__ABU_ASSET_BASE__||"/";
  return <div className="aa-login-page" dir="rtl">
    <div className="aa-login-top"><Brand/><Button kind="secondary" icon="home" onClick={()=>go("/")}>الرئيسية</Button></div>
    <main className="aa-login-shell">
      <section className="aa-login-story"><img src={`${assetBase}assets/hero-kids.webp`} alt="طفلان يتعلمان القرآن"/><div className="aa-login-story-copy"><span>لطفل صغير، خطوة واحدة في كل مرة</span><h1>الحفظ والمراجعة واللعب في رحلة واحدة واضحة</h1><p>واجهة الطفل بسيطة، وحساب الأسرة والمعلم يحتفظان بالمتابعة والتقدم.</p></div></section>
      <section className="aa-login-card"><h2>{heading}</h2><p>{description}</p>
        {!user&&mode!=="recover"&&<div className="aa-tabs"><button type="button" className={mode==="login"?"is-active":""} onClick={()=>changeMode("login")}>تسجيل الدخول</button><button type="button" className={mode==="signup"?"is-active":""} onClick={()=>changeMode("signup")}>حساب جديد</button></div>}
        {mode==="signup"&&<div className="aa-tabs"><button type="button" className={role==="parent"?"is-active":""} onClick={()=>setRole("parent")}>ولي أمر</button><button type="button" className={role==="teacher"?"is-active":""} onClick={()=>setRole("teacher")}>معلم</button></div>}
        <form className="aa-form" onSubmit={submit}>{mode==="signup"&&<label>الاسم<input value={name} onChange={e=>setName(e.target.value)} placeholder={role==="teacher"?"اسم المعلم":"اسم ولي الأمر"} required/></label>}{mode!=="update"&&<label>البريد الإلكتروني<input type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="name@example.com" required/></label>}{(mode==="login"||mode==="signup"||mode==="update")&&<label>{mode==="update"?"كلمة المرور الجديدة":"كلمة المرور"}<input type="password" minLength="6" autoComplete={mode==="login"?"current-password":"new-password"} value={password} onChange={e=>setPassword(e.target.value)} required/></label>}{mode==="signup"&&role==="parent"&&<div className="aa-selection-grid"><label>اسم الطفل<input value={childName} onChange={e=>setChildName(e.target.value)} required/></label><label>العمر<input type="number" min="3" max="18" value={ageYears} onChange={e=>setAgeYears(e.target.value)} required/></label><label>الفئة<select value={ageBand} onChange={e=>setAgeBand(e.target.value)}><option value="3-6">٣–٦ سنوات</option><option value="7-9">٧–٩ سنوات</option><option value="10-12">١٠–١٢ سنة</option></select></label><label>الجنس<select value={gender} onChange={e=>setGender(e.target.value)}><option value="unspecified">غير محدد</option><option value="male">ولد</option><option value="female">بنت</option></select></label></div>}{error&&<div className="msg error">{error}</div>}{message&&<div className="msg ok">{message}</div>}<Button type="submit" className="full" disabled={busy}>{busy?"جارٍ التنفيذ...":mode==="login"?"تسجيل الدخول":mode==="signup"?"إنشاء الحساب":mode==="recover"?"إرسال رابط الاستعادة":"حفظ كلمة المرور"}</Button></form>
        {!user&&mode==="login"&&<Button kind="ghost" onClick={()=>changeMode("recover")}>نسيت كلمة المرور؟</Button>}{!user&&mode==="recover"&&<Button kind="ghost" onClick={()=>changeMode("login")}>العودة لتسجيل الدخول</Button>}{user&&mode==="update"&&<Button kind="ghost" onClick={()=>go(user.accountType==="teacher"?"/teacher":"/family")}>العودة إلى حسابي</Button>}
      </section>
    </main>
  </div>;
}
