import React,{useEffect,useMemo,useState} from "react";
import {claimReward,dayKey,getActiveChildId,getCurrentUser,getProgress,listChildren,saveProgress,setActiveChildId} from "./api.js";
import {isChildModeActive} from "./ChildHub.jsx";
import {getSurah,SHORT_SURAH_ORDER,SURAHS} from "./surahCatalog.js";
import {selectSurah,selectedSurahNumber} from "./QuranPage.jsx";
import Icon from "./Icon.jsx";
import {AppShell,Button,CHILD_NAV,FAMILY_NAV,Hero,ProgressBar,Ring,Section,go} from "./ui-v4.jsx";

function sessionAyahCount(total){if(total<=7)return 1;if(total<=15)return 2;if(total<=40)return 3;if(total<=100)return 5;return 7;}

export default function MemorizePage(){
  const [user,setUser]=useState(undefined),[child,setChild]=useState(null),[progress,setProgress]=useState([]),[surahNumber,setSurahNumber]=useState(selectedSurahNumber()),[message,setMessage]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false);
  useEffect(()=>{let alive=true;(async()=>{try{const current=await getCurrentUser();if(!alive)return;if(!current)return go("/login");if(current.accountType==="teacher")return go("/teacher");setUser(current);const kids=await listChildren(current);if(!alive)return;const active=getActiveChildId();const selected=kids.find(k=>k.id===active)||kids[0]||null;if(selected&&selected.id!==active)setActiveChildId(selected.id);setChild(selected);if(!selected){setError("أضف طفلًا أولًا من حساب الأسرة.");return;}const rows=await getProgress(selected.id);if(!alive)return;setProgress(rows||[]);if(!getSurah(selectedSurahNumber())){const next=SHORT_SURAH_ORDER.find(n=>Number(rows.find(r=>Number(r.surah_number)===n)?.memorized_percent||0)<100)||1;setSurahNumber(next);selectSurah(next);}}catch(e){if(alive)setError(e.message||"تعذر تجهيز جلسة الحفظ.");}})();return()=>{alive=false;};},[]);
  const row=useMemo(()=>progress.find(p=>Number(p.surah_number)===Number(surahNumber)),[progress,surahNumber]);
  const surah=getSurah(surahNumber)||SURAHS[0];const currentPercent=Number(row?.memorized_percent||0);const currentAyahs=currentPercent>=100?surah.ayahs:Math.min(surah.ayahs,Math.floor((currentPercent/100)*surah.ayahs));const batch=sessionAyahCount(surah.ayahs);const nextAyahs=Math.min(surah.ayahs,currentAyahs+batch);const nextPercent=nextAyahs>=surah.ayahs?100:Math.max(currentPercent+1,Math.round((nextAyahs/surah.ayahs)*100));const childMode=isChildModeActive();
  function changeSurah(value){const n=Number(value);setSurahNumber(n);selectSurah(n);setMessage("");setError("");}
  async function complete(){if(!child?.id)return go("/family");if(currentPercent>=100)return go("/review");setBusy(true);setMessage("");setError("");try{await saveProgress({child_id:child.id,surah_number:surah.number,surah_name:surah.name,memorized_percent:nextPercent,review_percent:Number(row?.review_percent||0),status:nextPercent>=100?"review":"learning"});const reward=await claimReward(child.id,"memorize_session",dayKey("memorize",surah.number)).catch(()=>null);const value=Array.isArray(reward)?reward[0]:reward;setMessage(nextPercent>=100?`ما شاء الله! اكتمل حفظ سورة ${surah.name}.`:value?.awarded===false?`تم حفظ التقدم حتى الآية ${nextAyahs}. مكافأة اليوم حصلت عليها مسبقًا.`:`تم حفظ التقدم حتى الآية ${nextAyahs}. أحسنت!`);setProgress(await getProgress(child.id)||[]);}catch(e){setError(e.message||"تعذر حفظ تقدم الجلسة.");}finally{setBusy(false);}}
  if(user===undefined)return <div className="center"><i className="spinner"/><p>جارٍ تجهيز جلسة الحفظ...</p></div>;
  const actions=<><Button kind="secondary" icon="quran" onClick={()=>go("/quran")}>السور</Button>{!childMode&&<Button kind="secondary" icon="users" onClick={()=>go("/family")}>حساب الأسرة</Button>}</>;
  return <AppShell mode={childMode?"child":"family"} subtitle="جلسة الحفظ" nav={childMode?CHILD_NAV:FAMILY_NAV} actions={actions} footer="أبو العزايم • خطوة قصيرة وثابتة أفضل من جلسة طويلة مرهقة.">
    <Hero eyebrow="جلسة اليوم" title={`سورة ${surah.name}`} description={child?`جلسة خفيفة لـ ${child.display_name}. الهدف صغير وواضح، وبعدها نحفظ التقدم.`:"اختر طفلًا لبدء الحفظ."} icon="quran" tone="sky" aside={<Ring value={currentPercent} label="محفوظ"/>}/>
    {error&&<div className="msg error">{error}</div>}{message&&<div className="msg ok">{message}</div>}
    <div className="aa-learning-grid">
      <section className="aa-learning-card"><div className="aa-section-head"><div><span>السورة الحالية</span><h2>اختار السورة</h2></div></div><div className="aa-form"><select value={surah.number} onChange={e=>changeSurah(e.target.value)}>{SURAHS.map(s=><option key={s.number} value={s.number}>{s.number}. {s.name} — {s.ayahs} آية</option>)}</select></div><div className="aa-stat-row" style={{marginTop:14}}><div className="aa-stat-box"><b>{currentAyahs}</b><span>محفوظة</span></div><div className="aa-stat-box"><b>{surah.ayahs}</b><span>إجمالي</span></div><div className="aa-stat-box"><b>{Math.max(0,surah.ayahs-currentAyahs)}</b><span>متبقية</span></div></div><div style={{marginTop:16}}><ProgressBar value={currentPercent} label="تقدم الحفظ"/></div></section>
      <aside className="aa-learning-side"><section className="aa-learning-card"><div className="aa-learning-target"><span><Icon name={currentPercent>=100?"circleCheck":"target"} size={28}/></span><div><small>{currentPercent>=100?"الخطوة التالية":"هدف الجلسة"}</small><b>{currentPercent>=100?"ثبّت الحفظ بالمراجعة":`الآيات ${currentAyahs+1}–${nextAyahs}`}</b></div></div>{currentPercent<100?<><p style={{color:"var(--aa-muted)",lineHeight:1.8,fontSize:13}}>خذ وقتك في التكرار. لما تخلص الجزء الصغير ده، سجّل التقدم مرة واحدة.</p><Button className="full" disabled={busy||!child} onClick={complete}>{busy?"جارٍ حفظ التقدم...":`خلصت الآيات ${currentAyahs+1}–${nextAyahs}`}</Button></>:<><p style={{color:"var(--aa-muted)",lineHeight:1.8,fontSize:13}}>السورة محفوظة كاملة. دلوقتي نثبتها بدل إضافة حمل جديد.</p><Button className="full" icon="review" onClick={()=>go("/review")}>ابدأ المراجعة</Button></>}</section></aside>
    </div>
    <Section eyebrow="نصيحة صغيرة" title="جلسة واحدة واضحة أفضل من خطوات كثيرة"><div className="aa-learning-target"><span><Icon name="sparkle" size={26}/></span><div><small>لطفل صغير</small><b>كرر بهدوء، وخلي النجاح سريع وواضح.</b></div></div></Section>
  </AppShell>;
}
