export const NEW_QURAN_GAME_DEFINITIONS=[
{id:"ayah-hunter",title:"صائد الآية",icon:"target",description:"التقط الآية الصحيحة من أوراق متحركة قبل أن تختفي.",ageRange:[4,12],educationalGoal:"الاستدعاء وتسلسل الآيات",difficultyLevels:["easy","medium","hard"],supportedQuestionTypes:["next_ayah"],requiredData:["ayah_text","surah"],rewards:{completion:true,mastery:true},scene:"star-forest",route:"/games/ayah-hunter"},
{id:"where-start",title:"من أين أبدأ؟",icon:"lock",description:"افتح البوابة التي تحمل بداية الآية الصحيحة واصعد البرج.",ageRange:[6,12],educationalGoal:"استدعاء بدايات الآيات",difficultyLevels:["easy","medium","hard"],supportedQuestionTypes:["ayah_beginning"],requiredData:["ayah_text","words"],rewards:{completion:true},scene:"lavender-tower",route:"/games/where-start"},
{id:"what-next",title:"ماذا يأتي بعد؟",icon:"arrow",description:"اختر مسار الآية التالية لتحرك الشخصية على الطريق.",ageRange:[4,12],educationalGoal:"تثبيت التسلسل القرآني",difficultyLevels:["easy","medium","hard"],supportedQuestionTypes:["next_ayah"],requiredData:["ayah_text"],rewards:{completion:true},scene:"three-roads",route:"/games/what-next"},
{id:"build-ayah",title:"ابنِ الآية",icon:"puzzle",description:"حرّك قطع الكلمات حتى تبني الآية كاملة.",ageRange:[4,12],educationalGoal:"ترتيب كلمات الآية",difficultyLevels:["easy","medium","hard"],supportedQuestionTypes:["word_order"],requiredData:["ayah_text","words"],rewards:{completion:true,mastery:true},scene:"puzzle-table",route:"/games/build-ayah"},
{id:"memory-race",title:"سباق الذاكرة",icon:"bolt",description:"تقدم في طريق متغير كلما استدعيت الآية التالية.",ageRange:[4,12],educationalGoal:"الاستدعاء السريع",difficultyLevels:["easy","medium","hard"],supportedQuestionTypes:["next_ayah"],requiredData:["ayah_text"],rewards:{completion:true},scene:"memory-race",route:"/games/memory-race"},
{id:"surah-treasure",title:"كنز السورة",icon:"gift",description:"افتح محطات خريطة السورة حتى تصل إلى صندوق الكنز.",ageRange:[4,12],educationalGoal:"مراجعة السورة عبر مهام قصيرة",difficultyLevels:["easy","medium","hard"],supportedQuestionTypes:["next_ayah","ayah_beginning"],requiredData:["ayah_text","surah"],rewards:{completion:true,mastery:true},scene:"treasure-map",route:"/games/surah-treasure"},
{id:"similarity-mirror",title:"مرآة المتشابهات",icon:"search",description:"قارن مقطعين واكتشف الكلمات المختلفة داخل المرآتين.",ageRange:[7,12],educationalGoal:"تمييز التشابه والاختلاف اللفظي",difficultyLevels:["medium","hard"],supportedQuestionTypes:["similar_words"],requiredData:["ayah_text","words"],rewards:{completion:true},scene:"mirror-room",route:"/games/similarity-mirror"},
{id:"where-mentioned",title:"أين وردت؟",icon:"quran",description:"اربط المقطع بالسورة الصحيحة من السور التي درستها.",ageRange:[7,12],educationalGoal:"ربط الآيات بسورها",difficultyLevels:["easy","medium","hard"],supportedQuestionTypes:["surah_name"],requiredData:["ayah_text","surah"],rewards:{completion:true},scene:"surah-gates",route:"/games/where-mentioned"},
{id:"similarity-boxes",title:"صندوق المتشابهات",icon:"gift",description:"اختر صندوقًا وافتح تحديًا قصيرًا متغيرًا.",ageRange:[7,12],educationalGoal:"مراجعة المتشابهات بطريقة متنوعة",difficultyLevels:["medium","hard"],supportedQuestionTypes:["next_ayah"],requiredData:["ayah_text"],rewards:{completion:true},scene:"mystery-boxes",route:"/games/similarity-boxes"},
{id:"missing-word-adventure",title:"كلمة ضائعة",icon:"search",description:"ابحث عن الكلمة المفقودة بين كلمات متحركة.",ageRange:[4,12],educationalGoal:"استدعاء كلمات الآية",difficultyLevels:["easy","medium","hard"],supportedQuestionTypes:["missing_word"],requiredData:["ayah_text","words"],rewards:{completion:true,mastery:true},scene:"word-field",route:"/games/missing-word-adventure"},
{id:"word-box",title:"صندوق الكلمات",icon:"gift",description:"فتش داخل الصندوق عن كلمة موجودة في الآية.",ageRange:[4,9],educationalGoal:"الانتباه للكلمات القرآنية",difficultyLevels:["easy","medium"],supportedQuestionTypes:["word_recognition"],requiredData:["ayah_text","words"],rewards:{completion:true},scene:"word-box",route:"/games/word-box"}
];
export const newGameDefinition=id=>NEW_QURAN_GAME_DEFINITIONS.find(g=>g.id===id)||null;
