import React, { useEffect, useMemo, useRef, useState } from "react";
import Icon from "./Icon.jsx";
import { getProgress } from "./api.js";
import { loadLearningViewer, learningActorReady } from "./learningViewer.js";
import { getSurahAyahs, loadQuranData } from "./quranCorpus.js";
import { GameEngine, gameResultSummary } from "./gameEngine.js";
import { SoundEngine } from "./soundEngine.js";

const SAFE_SHORT_SURAHS=[112,113,114,108,109,110,111,103,104,105,106,107,67];
function routePath(){return typeof window.__ABU_ROUTE_PATH__==="function"?window.__ABU_ROUTE_PATH__():window.location.pathname;}
function navigate(path){if(routePath()!==path){history.pushState({},"",path);window.dispatchEvent(new PopStateEvent("popstate"));}}
function shuffle(items){const out=[...items];for(let i=out.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[out[i],out[j]]=[out[j],out[i]];}return out;}
function randomItem(items){return items[Math.floor(Math.random()*items.length)];}
function elapsed(start){return Math.max(0,Math.round(performance.now()-start.current));}

function useRuntime(gameId){
  const [viewer,setViewer]=useState(undefined);const [quran,setQuran]=useState(null);const [surahChoices,setSurahChoices]=useState([]);const [difficulty,setDifficulty]=useState("easy");const [error,setError]=useState("");
  useEffect(()=>{let alive=true;(async()=>{try{const context=await loadLearningViewer();if(!alive)return;if(!context.user)return navigate("/login");const data=await loadQuranData();if(!alive)return;let choices=SAFE_SHORT_SURAHS;if(!context.teacherPreview&&context.child?.id){const progress=await getProgress(context.child.id);const studied=(progress||[]).filter(p=>Number(p.memorized_percent||0)>0).map(p=>Number(p.surah_number));if(studied.length)choices=[...new Set(studied)];}setViewer(context);setQuran(data);setSurahChoices(choices.filter(n=>data.surahs.some(s=>s.number===n)));}catch(e){if(alive)setError(e.message||"تعذر تجهيز اللعبة.");}})();return()=>{alive=false;};},[gameId]);
  const makeEngine=()=>new GameEngine({childId:viewer?.child?.id,gameId,teacherPreview:Boolean(viewer?.teacherPreview)});
  return {viewer,quran,surahChoices,difficulty,setDifficulty,error,setError,makeEngine};
}
function Difficulty({value,onChange}){return <div className="difficulty-tabs">{[["easy","سهل"],["medium","متوسط"],["hard","متقدم"]].map(([v,label])=><button key={v} className={value===v?"active":""} onClick={()=>onChange(v)}>{label}</button>)}</div>;}
function Header({title,subtitle}){return <header className="game-topbar"><div className="wrap nav"><button className="brand" onClick={()=>navigate("/games")}><span className="logo"><Icon name="game" size={22}/></span><span><b>{title}</b><small>{subtitle}</small></span></button><div className="actions"><button className="secondary" onClick={()=>navigate("/games")}><Icon name="arrow" size={17}/> عالم الألعاب</button></div></div></header>;}
function Shell({title,subtitle,children}){return <div className="app quran-game-system quran-game-batch3" dir="rtl"><Header title={title} subtitle={subtitle}/><main className="wrap page qgame-page">{children}</main><footer><div className="wrap">الأسئلة تُبنى من QuranData المرجعي، والنتائج تدخل GameEngine والمراجعة الذكية.</div></footer></div>;}
function Result({session,onAgain}){const r=gameResultSummary(session);if(!r)return null;return <section className="qgame-result"><span className="qgame-result-icon"><Icon name="trophy" size={42}/></span><h2>اكتملت الجولة</h2><div className="result-stars">{[1,2,3].map(n=><span key={n} className={n<=r.stars?"earned":""}><Icon name="star" size={28}/></span>)}</div><div className="qgame-result-stats"><div><b>{r.score}</b><small>نقطة</small></div><div><b>{r.accuracy}%</b><small>دقة</small></div><div><b>{r.correct}</b><small>صحيح</small></div><div><b>{r.wrong}</b><small>خطأ</small></div></div><div className="row" style={{justifyContent:"center"}}><button className="secondary" onClick={()=>navigate("/games")}>العالم</button><button className="primary" onClick={onAgain}>جولة جديدة</button></div></section>;}
function pickVerse(verses,minWords=3){const good=verses.filter(v=>(v.words?.length||0)>=minWords);return randomItem(good.length?good:verses);}

export function GuessSurahGame(){
  const rt=useRuntime("guess-surah");const {viewer,quran,surahChoices,difficulty,setDifficulty,error,setError}=rt;const [question,setQuestion]=useState(null);const [engine,setEngine]=useState(null);const [result,setResult]=useState(null);const start=useRef(0);
  async function newRound(){setError("");setResult(null);const surahNumber=randomItem(surahChoices);const verses=await getSurahAyahs(surahNumber);const ayah=pickVerse(verses,difficulty==="hard"?6:3);const target=quran.surahs.find(s=>s.number===surahNumber);const pool=quran.surahs.filter(s=>s.number!==surahNumber);const distractors=shuffle(pool).slice(0,difficulty==="easy"?3:4);const options=shuffle([target,...distractors]);const eng=rt.makeEngine();await eng.start({difficulty,surahNumber,ayahNumbers:[ayah.ayahNumber]});setQuestion({ayah,target,options});setEngine(eng);start.current=performance.now();}
  useEffect(()=>{if(viewer&&quran&&surahChoices.length&&!engine&&!result)newRound().catch(e=>setError(e.message));},[viewer,quran,surahChoices.length,difficulty]);
  async function answer(surah){if(!question||!engine)return;const ok=surah.number===question.target.number;const ms=elapsed(start);await engine.recordAnswer({surahNumber:question.ayah.surahNumber,ayahNumber:question.ayah.ayahNumber,questionType:"surah_name",correct:ok,responseTimeMs:ms,metadata:{selectedSurah:surah.number}});if(!ok){SoundEngine.wrong();setError("ليست هذه السورة. اقرأ الآية مرة أخرى واربطها بموضعها.");return;}SoundEngine.correct();const done=await engine.complete({elapsedSeconds:Math.round(ms/1000)});SoundEngine.win();setResult(done);}
  if(viewer===undefined)return <div className="center"><i className="spinner"/><p>جارٍ تجهيز المختبر...</p></div>;
  return <Shell title="خمّن السورة" subtitle="اربط الآية بسورتها"><section className="qgame-intro"><div><span>مختبر السور</span><h1>من أي سورة هذه الآية؟</h1><p>اقرأ الآية جيدًا ثم اختر اسم السورة الصحيح.</p></div><Difficulty value={difficulty} onChange={v=>{setDifficulty(v);setEngine(null);setQuestion(null);}}/></section>{error&&<div className="msg error">{error}</div>}{result?<Result session={result} onAgain={()=>{setEngine(null);setQuestion(null);setResult(null);}}/>:<section className="game-stage guess-stage">{question&&<><blockquote className="quran-text">{question.ayah.text}</blockquote><div className="surah-choice-grid">{question.options.map(s=><button key={s.number} disabled={!learningActorReady(viewer)} onClick={()=>answer(s)}><span>{s.number}</span><b>سورة {s.name}</b></button>)}</div></>}</section>}</Shell>;
}

function makeMissing(ayah,verses,difficulty){const words=ayah.words||[];const candidates=words.map((w,i)=>({w,i})).filter(x=>x.i>0&&x.i<words.length-1);if(!candidates.length)return null;const target=randomItem(candidates);const wanted=difficulty==="easy"?5:difficulty==="medium"?7:9;const distractors=shuffle(verses.flatMap(v=>v.words||[]).filter(w=>w.text!==target.w.text)).slice(0,wanted-1);return {ayah,target,prompt:words.map((w,i)=>i===target.i?"ــــــ":w.text).join(" "),options:shuffle([target.w.text,...distractors.map(w=>w.text)])};}
export function WordHunterGame(){
  const rt=useRuntime("word-hunter");const {viewer,surahChoices,difficulty,setDifficulty,error,setError}=rt;const [q,setQ]=useState(null);const [engine,setEngine]=useState(null);const [result,setResult]=useState(null);const start=useRef(0);
  async function newRound(){setResult(null);setError("");const surah=randomItem(surahChoices);const verses=await getSurahAyahs(surah);let question=null;for(let i=0;i<10&&!question;i++)question=makeMissing(pickVerse(verses,4),verses,difficulty);if(!question)throw new Error("تعذر إنشاء سؤال كلمات مناسب.");const eng=rt.makeEngine();await eng.start({difficulty,surahNumber:surah,ayahNumbers:[question.ayah.ayahNumber]});setQ(question);setEngine(eng);start.current=performance.now();}
  useEffect(()=>{if(viewer&&surahChoices.length&&!engine&&!result)newRound().catch(e=>setError(e.message));},[viewer,surahChoices.length,difficulty]);
  async function hit(word){if(!q||!engine)return;const ok=word===q.target.w.text;const ms=elapsed(start);await engine.recordAnswer({surahNumber:q.ayah.surahNumber,ayahNumber:q.ayah.ayahNumber,questionType:"missing_word",correct:ok,responseTimeMs:ms,metadata:{selectedWord:word}});if(!ok){SoundEngine.wrong();setError("هذه ليست الكلمة المطلوبة. جرّب كلمة أخرى.");return;}SoundEngine.correct();const done=await engine.complete({elapsedSeconds:Math.round(ms/1000)});SoundEngine.win();setResult(done);}
  if(viewer===undefined)return <div className="center"><i className="spinner"/><p>جارٍ تجهيز ساحة الصيد...</p></div>;
  return <Shell title="صائد الكلمات" subtitle="التقط الكلمة الناقصة"><section className="qgame-intro"><div><span>سرعة الاستدعاء</span><h1>اصطد الكلمة التي تكمل الآية</h1><p>الكلمات تتحرك في الساحة، لكن واحدة فقط تكمل النص المرجعي.</p></div><Difficulty value={difficulty} onChange={v=>{setDifficulty(v);setEngine(null);setQ(null);}}/></section>{error&&<div className="msg error">{error}</div>}{result?<Result session={result} onAgain={()=>{setEngine(null);setQ(null);setResult(null);}}/>:<section className="game-stage hunter-stage">{q&&<><blockquote className="quran-text">{q.prompt}</blockquote><div className="word-hunt-field">{q.options.map((w,i)=><button key={`${w}-${i}`} style={{"--delay":`${(i%5)*.13}s`}} disabled={!learningActorReady(viewer)} onClick={()=>hit(w)}><Icon name="target" size={18}/><b>{w}</b></button>)}</div></>}</section>}</Shell>;
}

function selectUniqueAyahs(verses,count){const out=[],beg=new Set(),end=new Set();for(const v of shuffle(verses.filter(x=>(x.words?.length||0)>=6))){const b=v.words.slice(0,3).map(w=>w.text).join(" "),e=v.words.slice(-3).map(w=>w.text).join(" ");if(beg.has(b)||end.has(e))continue;beg.add(b);end.add(e);out.push({...v,beginText:b,endText:e});if(out.length===count)break;}return out;}
export function AyahMatchingGame(){
  const rt=useRuntime("ayah-matching");const {viewer,surahChoices,difficulty,setDifficulty,error,setError}=rt;const [left,setLeft]=useState([]),[right,setRight]=useState([]),[selected,setSelected]=useState(null),[matched,setMatched]=useState([]),[engine,setEngine]=useState(null),[result,setResult]=useState(null);const start=useRef(0);
  async function newRound(){setResult(null);setError("");setSelected(null);setMatched([]);const surah=randomItem(surahChoices);const verses=await getSurahAyahs(surah);const count=difficulty==="easy"?3:difficulty==="medium"?4:5;const picked=selectUniqueAyahs(verses,count);if(picked.length<3)throw new Error("لا توجد آيات كافية لمطابقة بدايات ونهايات مختلفة.");const eng=rt.makeEngine();await eng.start({difficulty,surahNumber:surah,ayahNumbers:picked.map(v=>v.ayahNumber)});setLeft(picked);setRight(shuffle(picked));setEngine(eng);start.current=performance.now();}
  useEffect(()=>{if(viewer&&surahChoices.length&&!engine&&!result)newRound().catch(e=>setError(e.message));},[viewer,surahChoices.length,difficulty]);
  async function chooseEnd(v){if(!selected||matched.includes(v.key))return;const ok=selected.key===v.key;const ms=elapsed(start);if(ok){await engine.recordAnswer({surahNumber:v.surahNumber,ayahNumber:v.ayahNumber,questionType:"beginning_ending",correct:true,responseTimeMs:ms});SoundEngine.correct();const next=[...matched,v.key];setMatched(next);setSelected(null);setError("");if(next.length===left.length){const done=await engine.complete({elapsedSeconds:Math.round(ms/1000)});SoundEngine.win();setResult(done);}return;}await engine.recordAnswer({surahNumber:selected.surahNumber,ayahNumber:selected.ayahNumber,questionType:"beginning_ending",correct:false,responseTimeMs:ms,metadata:{selectedEnding:v.ayahNumber}});SoundEngine.wrong();setError("النهاية لا تخص هذه البداية. اختر نهاية أخرى.");}
  if(viewer===undefined)return <div className="center"><i className="spinner"/><p>جارٍ تجهيز لوحة المطابقة...</p></div>;
  return <Shell title="مطابقة الآيات" subtitle="صل البداية بالنهاية"><section className="qgame-intro"><div><span>ربط بصري</span><h1>اختر بداية ثم النهاية الصحيحة</h1><p>كل سطر مأخوذ من آية حقيقية، والمطلوب ربط الطرفين من الآية نفسها.</p></div><Difficulty value={difficulty} onChange={v=>{setDifficulty(v);setEngine(null);setLeft([]);setRight([]);setMatched([]);}}/></section>{error&&<div className="msg error">{error}</div>}{result?<Result session={result} onAgain={()=>{setEngine(null);setLeft([]);setRight([]);setMatched([]);setResult(null);}}/>:<section className="game-stage matching-stage"><div className="matching-columns"><div><h3>بدايات الآيات</h3>{left.map(v=><button key={v.key} className={`${selected?.key===v.key?"selected":""} ${matched.includes(v.key)?"matched":""}`} disabled={matched.includes(v.key)||!learningActorReady(viewer)} onClick={()=>{setSelected(v);SoundEngine.tap();}}>{v.beginText}</button>)}</div><div><h3>نهايات الآيات</h3>{right.map(v=><button key={v.key} className={matched.includes(v.key)?"matched":""} disabled={matched.includes(v.key)||!selected||!learningActorReady(viewer)} onClick={()=>chooseEnd(v)}>{v.endText}</button>)}</div></div><small className="matching-progress">تمت مطابقة {matched.length} من {left.length}</small></section>}</Shell>;
}

function consecutiveSurahs(surahs,count){if(surahs.length<count)return [];const start=Math.floor(Math.random()*(surahs.length-count+1));return surahs.slice(start,start+count);}
export function SurahCardsGame(){
  const rt=useRuntime("surah-cards");const {viewer,quran,difficulty,setDifficulty,error,setError}=rt;const [correct,setCorrect]=useState([]),[cards,setCards]=useState([]),[engine,setEngine]=useState(null),[result,setResult]=useState(null);const start=useRef(0);
  async function newRound(){if(!quran)return;setResult(null);setError("");const count=difficulty==="easy"?4:difficulty==="medium"?5:6;const group=consecutiveSurahs(quran.surahs,count);const eng=rt.makeEngine();await eng.start({difficulty,surahNumber:null,ayahNumbers:[]});setCorrect(group);setCards(shuffle(group));setEngine(eng);start.current=performance.now();}
  useEffect(()=>{if(viewer&&quran&&!engine&&!result)newRound().catch(e=>setError(e.message));},[viewer,quran,difficulty]);
  function shift(index,dir){const to=index+dir;if(to<0||to>=cards.length)return;setCards(prev=>{const n=[...prev];[n[index],n[to]]=[n[to],n[index]];return n;});SoundEngine.tap();}
  async function verify(){const ok=cards.every((s,i)=>s.number===correct[i]?.number);const ms=elapsed(start);const anchor=correct[0]?.number||1;await engine.recordAnswer({surahNumber:anchor,ayahNumber:1,questionType:"surah_order",correct:ok,responseTimeMs:ms,metadata:{expected:correct.map(s=>s.number),submitted:cards.map(s=>s.number)}});if(!ok){SoundEngine.wrong();setError("ترتيب السور غير صحيح بعد. استخدم الأرقام أو معرفتك بالترتيب وحاول.");return;}SoundEngine.correct();const done=await engine.complete({elapsedSeconds:Math.round(ms/1000)});SoundEngine.win();setResult(done);}
  if(viewer===undefined)return <div className="center"><i className="spinner"/><p>جارٍ تجهيز بطاقات السور...</p></div>;
  return <Shell title="البطاقات العشوائية" subtitle="رتّب السور المتتالية"><section className="qgame-intro"><div><span>ترتيب المصحف</span><h1>أعد السور إلى ترتيبها الصحيح</h1><p>المجموعة متتالية في المصحف، حرّك البطاقات حتى تصبح من الأصغر للأكبر في الترتيب.</p></div><Difficulty value={difficulty} onChange={v=>{setDifficulty(v);setEngine(null);setCards([]);setCorrect([]);}}/></section>{error&&<div className="msg error">{error}</div>}{result?<Result session={result} onAgain={()=>{setEngine(null);setCards([]);setCorrect([]);setResult(null);}}/>:<section className="game-stage surah-card-stage"><div className="surah-order-cards">{cards.map((s,i)=><article key={s.number}><span>{s.number}</span><b>سورة {s.name}</b><div><button onClick={()=>shift(i,-1)} disabled={i===0}>→</button><button onClick={()=>shift(i,1)} disabled={i===cards.length-1}>←</button></div></article>)}</div><button className="primary full" disabled={!engine||!cards.length} onClick={verify}><Icon name="check" size={18}/> تحقق من الترتيب</button></section>}</Shell>;
}
