import React, { useEffect, useMemo, useRef, useState } from "react";
import Icon from "./Icon.jsx";
import { getProgress } from "./api.js";
import { loadLearningViewer, learningActorReady } from "./learningViewer.js";
import { getSurahAyahs, loadQuranData } from "./quranCorpus.js";
import { GameEngine, gameResultSummary } from "./gameEngine.js";
import { SoundEngine } from "./soundEngine.js";

const SAFE_SHORT_SURAHS=[112,113,114,108,109,110,111,103,104,105,106,107,67];
function routePath(){return typeof window.__ABU_ROUTE_PATH__==="function"?window.__ABU_ROUTE_PATH__():window.location.pathname;}
function navigate(path){if(routePath()!==path){history.pushState({},"",path);window.dispatchEvent(new PopStateEvent("popstate"));}}
function shuffle(items){const out=[...items];for(let i=out.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[out[i],out[j]]=[out[j],out[i]];}return out;}
function randomItem(items){return items[Math.floor(Math.random()*items.length)];}
function msSince(ref){return Math.max(0,Math.round(performance.now()-ref.current));}

function useRuntime(gameId){
  const [viewer,setViewer]=useState(undefined);const [quran,setQuran]=useState(null);const [surahChoices,setSurahChoices]=useState([]);const [difficulty,setDifficulty]=useState("easy");const [error,setError]=useState("");
  useEffect(()=>{let alive=true;(async()=>{try{const context=await loadLearningViewer();if(!alive)return;if(!context.user)return navigate("/login");const data=await loadQuranData();if(!alive)return;let choices=SAFE_SHORT_SURAHS;if(!context.teacherPreview&&context.child?.id){const rows=await getProgress(context.child.id);const studied=(rows||[]).filter(x=>Number(x.memorized_percent||0)>0).map(x=>Number(x.surah_number));if(studied.length)choices=[...new Set(studied)];}setViewer(context);setQuran(data);setSurahChoices(choices.filter(n=>data.surahs.some(s=>s.number===n)));}catch(e){if(alive)setError(e.message||"تعذر تجهيز اللعبة.");}})();return()=>{alive=false;};},[gameId]);
  return {viewer,quran,surahChoices,difficulty,setDifficulty,error,setError,makeEngine:()=>new GameEngine({childId:viewer?.child?.id,gameId,teacherPreview:Boolean(viewer?.teacherPreview)})};
}
function Difficulty({value,onChange}){return <div className="difficulty-tabs">{[["easy","سهل"],["medium","متوسط"],["hard","متقدم"]].map(([v,label])=><button key={v} className={value===v?"active":""} onClick={()=>onChange(v)}>{label}</button>)}</div>;}
function Header({title,subtitle}){const [sound,setSound]=useState(SoundEngine.isEnabled());return <header className="game-topbar"><div className="wrap nav"><button className="brand" onClick={()=>navigate("/games")}><span className="logo"><Icon name="game" size={22}/></span><span><b>{title}</b><small>{subtitle}</small></span></button><div className="actions"><button className="secondary" onClick={()=>{SoundEngine.setEnabled(!sound);setSound(!sound);}}><Icon name={sound?"sound":"mute"} size={17}/>{sound?"الصوت يعمل":"الصوت متوقف"}</button><button className="secondary" onClick={()=>navigate("/games")}><Icon name="arrow" size={17}/> عالم الألعاب</button></div></div></header>;}
function Shell({title,subtitle,children}){return <div className="app quran-game-system quran-game-batch4" dir="rtl"><Header title={title} subtitle={subtitle}/><main className="wrap page qgame-page">{children}</main><footer><div className="wrap">النص والأسئلة القرآنية تأتي من QuranData المرجعي، والأخطاء تدخل المراجعة الذكية تلقائيًا.</div></footer></div>;}
function Stars({count=0}){return <div className="result-stars">{[1,2,3].map(n=><span key={n} className={n<=count?"earned":""}><Icon name="star" size={28}/></span>)}</div>;}
function Result({session,onAgain,children}){const r=gameResultSummary(session);if(!r)return null;return <section className="qgame-result"><span className="qgame-result-icon"><Icon name="trophy" size={42}/></span><h2>اكتملت الجولة</h2><Stars count={r.stars}/><div className="qgame-result-stats"><div><b>{r.score}</b><small>نقطة</small></div><div><b>{r.accuracy}%</b><small>دقة</small></div><div><b>{r.correct}</b><small>صحيح</small></div><div><b>{r.wrong}</b><small>خطأ</small></div></div>{children}<div className="row" style={{justifyContent:"center"}}><button className="secondary" onClick={()=>navigate("/games")}>العالم</button><button className="primary" onClick={onAgain}>جولة جديدة</button></div></section>;}

function uniqueWords(verses,target,count){const seen=new Set([target]),out=[];for(const w of shuffle(verses.flatMap(v=>v.words||[]))){if(!w?.text||seen.has(w.text))continue;seen.add(w.text);out.push(w.text);if(out.length===count)break;}return out;}
function makeMissingQuestion(ayah,verses,difficulty){const words=ayah.words||[];const valid=words.map((w,i)=>({w,i})).filter(x=>x.i>0&&x.i<words.length-1);if(!valid.length)return null;const target=randomItem(valid);const distractors=uniqueWords(verses,target.w.text,difficulty==="easy"?3:4);return {kind:"missing_word",questionType:"missing_word",ayah,prompt:words.map((w,i)=>i===target.i?"ــــــ":w.text).join(" "),options:shuffle([target.w.text,...distractors]),answer:target.w.text,digit:String((target.i+1)%10)};}
function makeSurahQuestion(ayah,quran,difficulty){const target=quran.surahs.find(s=>s.number===ayah.surahNumber);const pool=shuffle(quran.surahs.filter(s=>s.number!==target.number)).slice(0,difficulty==="easy"?3:4);return {kind:"surah_name",questionType:"surah_name",ayah,prompt:ayah.text,options:shuffle([target,...pool]).map(s=>({value:String(s.number),label:`سورة ${s.name}`})),answer:String(target.number),digit:String(target.number%10)};}
function makeAyahNumberQuestion(ayah,verses,difficulty){const nums=new Set([ayah.ayahNumber]);for(const v of shuffle(verses)){if(nums.size>= (difficulty==="easy"?4:5))break;nums.add(v.ayahNumber);}return {kind:"ayah_number",questionType:"ayah_number",ayah,prompt:ayah.text,options:shuffle([...nums]).map(n=>({value:String(n),label:`الآية ${n}`})),answer:String(ayah.ayahNumber),digit:String(ayah.ayahNumber%10)};}

export function AyahCodeGame(){
  const rt=useRuntime("ayah-code");const {viewer,quran,surahChoices,difficulty,setDifficulty,error,setError}=rt;const [questions,setQuestions]=useState([]);const [index,setIndex]=useState(0);const [digits,setDigits]=useState([]);const [engine,setEngine]=useState(null);const [result,setResult]=useState(null);const started=useRef(0);
  const current=questions[index]||null;
  async function newGame(){if(!quran||!surahChoices.length)return;setError("");setResult(null);setDigits([]);setIndex(0);const chosenSurahs=shuffle(surahChoices).slice(0,Math.min(4,surahChoices.length));const built=[];for(let i=0;i<4;i++){const surah=chosenSurahs[i%chosenSurahs.length];const verses=await getSurahAyahs(surah);const candidates=verses.filter(v=>(v.words?.length||0)>=4);const ayah=randomItem(candidates.length?candidates:verses);let q;if(i===0)q=makeSurahQuestion(ayah,quran,difficulty);else if(i===1)q=makeAyahNumberQuestion(ayah,verses,difficulty);else q=makeMissingQuestion(ayah,verses,difficulty)||makeSurahQuestion(ayah,quran,difficulty);built.push(q);}const eng=rt.makeEngine();await eng.start({difficulty,surahNumber:null,ayahNumbers:built.map(q=>q.ayah.ayahNumber)});setQuestions(built);setEngine(eng);started.current=performance.now();}
  useEffect(()=>{if(viewer&&quran&&surahChoices.length&&!engine&&!result)newGame().catch(e=>setError(e.message));},[viewer,quran,surahChoices.length,difficulty]);
  async function answer(value){if(!current||!engine)return;const ok=String(value)===String(current.answer);const ms=msSince(started);await engine.recordAnswer({surahNumber:current.ayah.surahNumber,ayahNumber:current.ayah.ayahNumber,questionType:current.questionType,correct:ok,responseTimeMs:ms,metadata:{step:index+1,selected:String(value)}});if(!ok){SoundEngine.wrong();setError("الإجابة لا تفتح هذه الخانة. حاول مرة أخرى.");return;}SoundEngine.unlock();setError("");const nextDigits=[...digits,current.digit];setDigits(nextDigits);if(index===questions.length-1){const done=await engine.complete({elapsedSeconds:Math.round(ms/1000)});SoundEngine.win();setResult(done);return;}setIndex(x=>x+1);started.current=performance.now();}
  if(viewer===undefined)return <div className="center"><i className="spinner"/><p>جارٍ تجهيز الخزنة...</p></div>;
  return <Shell title="شفرة الآيات" subtitle="حل الأسئلة وافتح الخزنة"><section className="qgame-intro"><div><span>تحدي متعدد المراحل</span><h1>اجمع أرقام الشفرة الأربعة</h1><p>كل إجابة صحيحة تفتح خانة جديدة. الخطأ يُحفظ كآية تحتاج مراجعة.</p></div><Difficulty value={difficulty} onChange={v=>{setDifficulty(v);setEngine(null);setQuestions([]);}}/></section>{error&&<div className="msg error">{error}</div>}{result?<Result session={result} onAgain={()=>{setEngine(null);setQuestions([]);setResult(null);}}><div className="vault-open"><Icon name="unlock" size={34}/><b>تم فتح الخزنة بالشفرة {digits.join("")}</b></div></Result>:<section className="game-stage code-stage"><div className="vault-panel"><span className="vault-icon"><Icon name="lock" size={46}/></span><div className="code-slots">{[0,1,2,3].map(i=><span key={i} className={digits[i]!=null?"open":""}>{digits[i]??"·"}</span>)}</div><small>المرحلة {Math.min(index+1,4)} من 4</small></div>{current&&<div className="code-question"><span className="question-label">{current.kind==="surah_name"?"من أي سورة هذه الآية؟":current.kind==="ayah_number"?"ما رقم هذه الآية داخل السورة؟":"اختر الكلمة الناقصة"}</span><blockquote className="quran-text">{current.prompt}</blockquote><div className="code-options">{current.options.map((o,i)=>{const value=typeof o==="string"?o:o.value;const label=typeof o==="string"?o:o.label;return <button key={`${value}-${i}`} disabled={!learningActorReady(viewer)} onClick={()=>answer(value)}><span>{String.fromCharCode(65+i)}</span><b>{label}</b></button>;})}</div></div>}</section>}</Shell>;
}

function nextAyahQuestion(verses,index,difficulty){const current=verses[index],answer=verses[index+1];if(!current||!answer)return null;const pool=shuffle(verses.filter(v=>v.key!==answer.key&&v.key!==current.key)).slice(0,difficulty==="easy"?3:4);return {kind:"next_ayah",questionType:"next_ayah",ayah:answer,prompt:current.text,options:shuffle([answer,...pool]).map(v=>({value:v.key,label:v.text})),answer:answer.key};}
function beginQuestion(ayah,verses,difficulty){const words=ayah.words||[];const take=difficulty==="hard"?2:3;const beginning=words.slice(0,take).map(w=>w.text).join(" ");const options=[{value:ayah.key,label:beginning},...shuffle(verses.filter(v=>v.key!==ayah.key&&(v.words?.length||0)>=take)).slice(0,difficulty==="easy"?3:4).map(v=>({value:v.key,label:v.words.slice(0,take).map(w=>w.text).join(" ")}))];return {kind:"ayah_beginning",questionType:"ayah_beginning",ayah,prompt:`اختر بداية الآية رقم ${ayah.ayahNumber}`,options:shuffle(options),answer:ayah.key};}

export function SurahExamGame(){
  const rt=useRuntime("surah-exam");const {viewer,quran,surahChoices,difficulty,setDifficulty,error,setError}=rt;const [surah,setSurah]=useState(null);const [questions,setQuestions]=useState([]);const [index,setIndex]=useState(0);const [wrong,setWrong]=useState([]);const [engine,setEngine]=useState(null);const [result,setResult]=useState(null);const started=useRef(0);
  const current=questions[index]||null;
  async function buildExam(forcedSurah=null){if(!quran||!surahChoices.length)return;setError("");setResult(null);setWrong([]);setIndex(0);const surahNumber=Number(forcedSurah||randomItem(surahChoices));const verses=await getSurahAyahs(surahNumber);const eligible=verses.filter(v=>(v.words?.length||0)>=4);if(eligible.length<3)throw new Error("السورة قصيرة جدًا لهذا الاختبار. اختر سورة أخرى.");const q=[];const nextIndex=Math.max(0,Math.min(verses.length-2,Math.floor(Math.random()*Math.max(1,verses.length-1))));q.push(nextAyahQuestion(verses,nextIndex,difficulty));const missingAyah=randomItem(eligible);q.push(makeMissingQuestion(missingAyah,verses,difficulty));const surahAyah=randomItem(eligible);q.push(makeSurahQuestion(surahAyah,quran,difficulty));const numAyah=randomItem(eligible);q.push(makeAyahNumberQuestion(numAyah,verses,difficulty));const beginAyah=randomItem(eligible);q.push(beginQuestion(beginAyah,verses,difficulty));const built=q.filter(Boolean);const eng=rt.makeEngine();await eng.start({difficulty,surahNumber,ayahNumbers:[...new Set(built.map(x=>x.ayah.ayahNumber))]});setSurah(quran.surahs.find(s=>s.number===surahNumber));setQuestions(built);setEngine(eng);started.current=performance.now();}
  useEffect(()=>{if(viewer&&quran&&surahChoices.length&&!engine&&!result)buildExam().catch(e=>setError(e.message));},[viewer,quran,surahChoices.length,difficulty]);
  async function answer(value){if(!current||!engine)return;const ok=String(value)===String(current.answer);const ms=msSince(started);await engine.recordAnswer({surahNumber:current.ayah.surahNumber,ayahNumber:current.ayah.ayahNumber,questionType:current.questionType,correct:ok,responseTimeMs:ms,metadata:{examStep:index+1,selected:String(value)}});if(ok)SoundEngine.correct();else{SoundEngine.wrong();setWrong(prev=>prev.some(x=>x.key===current.ayah.key)?prev:[...prev,current.ayah]);}if(index===questions.length-1){const done=await engine.complete({elapsedSeconds:Math.round(ms/1000)});SoundEngine.win();setResult(done);return;}setIndex(x=>x+1);setError("");started.current=performance.now();}
  const options=useMemo(()=>current?.options||[],[current]);
  if(viewer===undefined)return <div className="center"><i className="spinner"/><p>جارٍ تجهيز اختبار السورة...</p></div>;
  return <Shell title="اختبار حفظ السورة" subtitle="قياس متنوع للحفظ"><section className="qgame-intro"><div><span>اختبار شامل</span><h1>{surah?`اختبار سورة ${surah.name}`:"تجهيز الاختبار"}</h1><p>خمسة أنواع أسئلة. أي آية تخطئ فيها تدخل تلقائيًا قائمة المراجعة الذكية.</p></div><div className="exam-controls"><Difficulty value={difficulty} onChange={v=>{setDifficulty(v);setEngine(null);setQuestions([]);}}/><select value={surah?.number||""} onChange={e=>{setEngine(null);setQuestions([]);buildExam(Number(e.target.value)).catch(err=>setError(err.message));}}><option value="" disabled>اختر السورة</option>{surahChoices.map(n=>{const s=quran?.surahs.find(x=>x.number===n);return <option key={n} value={n}>{n}. {s?.name||""}</option>;})}</select></div></section>{error&&<div className="msg error">{error}</div>}{result?<Result session={result} onAgain={()=>{setEngine(null);setQuestions([]);setResult(null);}}>{wrong.length?<div className="exam-review"><b>آيات تحتاج مراجعة</b><div>{wrong.map(v=><span key={v.key}>سورة {v.surahName} — آية {v.ayahNumber}</span>)}</div><small>تم إرسالها للمراجعة الذكية داخل حساب الطفل.</small></div>:<div className="exam-review mastered"><Icon name="check" size={24}/><b>لم تُسجل أخطاء في هذا الاختبار</b></div>}</Result>:<section className="game-stage exam-stage">{current&&<><div className="exam-progress"><span style={{width:`${((index+1)/questions.length)*100}%`}}/><small>السؤال {index+1} من {questions.length}</small></div><span className="question-label">{current.kind==="next_ayah"?"ما الآية التالية؟":current.kind==="missing_word"?"اختر الكلمة الناقصة":current.kind==="surah_name"?"من أي سورة هذه الآية؟":current.kind==="ayah_number"?"ما رقم الآية؟":"اختر بداية الآية الصحيحة"}</span><blockquote className="quran-text">{current.prompt}</blockquote><div className="exam-options">{options.map((o,i)=>{const value=typeof o==="string"?o:o.value;const label=typeof o==="string"?o:o.label;return <button key={`${value}-${i}`} disabled={!learningActorReady(viewer)} onClick={()=>answer(value)}><span>{i+1}</span><b>{label}</b></button>;})}</div></>}</section>}</Shell>;
}
