import React, { useEffect, useMemo, useRef, useState } from "react";
import Icon from "./Icon.jsx";
import { getProgress } from "./api.js";
import { loadLearningViewer, learningActorReady } from "./learningViewer.js";
import { getSurahAyahs, loadQuranData } from "./quranCorpus.js";
import { GameEngine, gameResultSummary } from "./gameEngine.js";
import { SoundEngine } from "./soundEngine.js";

function routePath(){return typeof window.__ABU_ROUTE_PATH__==="function"?window.__ABU_ROUTE_PATH__():window.location.pathname;}
function navigate(path){if(routePath()!==path){history.pushState({},"",path);window.dispatchEvent(new PopStateEvent("popstate"));}}
function shuffle(items){return [...items].sort(()=>Math.random()-.5);}
function randomItem(items){return items[Math.floor(Math.random()*items.length)];}
function clamp(n,min,max){return Math.max(min,Math.min(max,n));}

const SAFE_SHORT_SURAHS=[112,113,114,108,109,110,111,103,104,105,106,107,67];

function SoundToggle(){const [on,setOn]=useState(SoundEngine.isEnabled());return <button className="secondary game-sound-toggle" onClick={()=>{SoundEngine.setEnabled(!on);setOn(!on);}}><Icon name={on?"sound":"mute"} size={17}/>{on?"الصوت يعمل":"الصوت متوقف"}</button>;}

function GameHeader({title,subtitle}){return <header className="game-topbar"><div className="wrap nav"><button className="brand" onClick={()=>navigate("/games")}><span className="logo"><Icon name="game" size={22}/></span><span><b>{title}</b><small>{subtitle}</small></span></button><div className="actions"><SoundToggle/><button className="secondary" onClick={()=>navigate("/games")}><Icon name="arrow" size={17}/> عالم الألعاب</button></div></div></header>;}

function Stars({count=0}){return <div className="result-stars" aria-label={`${count} نجوم`}>{[1,2,3].map(n=><span key={n} className={n<=count?"earned":""}><Icon name="star" size={28}/></span>)}</div>;}

function ResultPanel({session,onAgain}){const r=gameResultSummary(session);if(!r)return null;return <section className="qgame-result"><span className="qgame-result-icon"><Icon name="trophy" size={42}/></span><h2>أحسنت، اكتملت الجولة</h2><Stars count={r.stars}/><div className="qgame-result-stats"><div><b>{r.score}</b><small>نقطة</small></div><div><b>{r.accuracy}%</b><small>دقة</small></div><div><b>{r.correct}</b><small>إجابة صحيحة</small></div><div><b>{r.wrong}</b><small>محاولة خاطئة</small></div></div>{session?.reward_awarded===false&&<p>تم حفظ أفضل نتيجتك، لكن مكافأة هذه اللعبة لليوم حصلت عليها مسبقًا.</p>}<div className="row" style={{justifyContent:"center"}}><button className="secondary" onClick={()=>navigate("/games")}>عالم الألعاب</button><button className="primary" onClick={onAgain}>العب جولة جديدة</button></div></section>;}

function useQuranGame(gameId){
  const [viewer,setViewer]=useState(undefined); const [quran,setQuran]=useState(null); const [surahChoices,setSurahChoices]=useState([]); const [difficulty,setDifficulty]=useState("easy"); const [error,setError]=useState("");
  useEffect(()=>{let alive=true;(async()=>{try{const context=await loadLearningViewer();if(!alive)return;if(!context.user)return navigate("/login");const data=await loadQuranData();if(!alive)return;let choices=SAFE_SHORT_SURAHS;if(!context.teacherPreview&&context.child?.id){const progress=await getProgress(context.child.id);const studied=(progress||[]).filter(p=>Number(p.memorized_percent||0)>0).map(p=>Number(p.surah_number));if(studied.length)choices=[...new Set(studied)];}setViewer(context);setQuran(data);setSurahChoices(choices.filter(n=>data.surahs.some(s=>s.number===n)));}catch(e){if(alive)setError(e.message||"تعذر تجهيز اللعبة.");}})();return()=>{alive=false;};},[gameId]);
  function engine(){return new GameEngine({childId:viewer?.child?.id,gameId,teacherPreview:Boolean(viewer?.teacherPreview)});}
  return {viewer,quran,surahChoices,difficulty,setDifficulty,error,setError,engine};
}

function Difficulty({value,onChange}){return <div className="difficulty-tabs">{[["easy","سهل"],["medium","متوسط"],["hard","متقدم"]].map(([v,label])=><button key={v} className={value===v?"active":""} onClick={()=>onChange(v)}>{label}</button>)}</div>;}

function QuranGameShell({title,subtitle,children}){return <div className="app quran-game-system" dir="rtl"><GameHeader title={title} subtitle={subtitle}/><main className="wrap page qgame-page">{children}</main><footer><div className="wrap">النص القرآني في الألعاب من QuranData الموثق بمصدر Tanzil، ولا يتم توليده داخل اللعبة.</div></footer></div>;}

export function QuranWheelGame(){
  const runtime=useQuranGame("quran-wheel"); const {viewer,surahChoices,difficulty,setDifficulty,error,setError}=runtime;
  const [rotation,setRotation]=useState(0); const [spinning,setSpinning]=useState(false); const [round,setRound]=useState(0); const [question,setQuestion]=useState(null); const [result,setResult]=useState(null); const [engine,setEngine]=useState(null); const startedAt=useRef(0);
  async function spin(){if(spinning||!surahChoices.length)return;setResult(null);setQuestion(null);setError("");setSpinning(true);let ticks=0;const tick=setInterval(()=>{SoundEngine.spin();if(++ticks>20)clearInterval(tick);},75);const chosen=randomItem(surahChoices);const extra=1440+Math.floor(Math.random()*720);setRotation(r=>r+extra);await new Promise(r=>setTimeout(r,2600));clearInterval(tick);try{const verses=await getSurahAyahs(chosen);if(verses.length<2)throw new Error("السورة قصيرة لهذا التحدي.");const max=verses.length-2;const index=Math.floor(Math.random()*(max+1));const current=verses[index];const answer=verses[index+1];const distractors=shuffle(verses.filter(v=>v.key!==answer.key&&Math.abs(v.ayahNumber-answer.ayahNumber)<=6)).slice(0,difficulty==="easy"?3:2);const options=shuffle([answer,...distractors]);const eng=runtime.engine();await eng.start({difficulty,surahNumber:chosen,ayahNumbers:[current.ayahNumber,answer.ayahNumber]});setEngine(eng);setQuestion({current,answer,options});startedAt.current=performance.now();setRound(x=>x+1);}catch(e){setError(e.message||"تعذر إنشاء التحدي.");}finally{setSpinning(false);}}
  async function answer(option){if(!question||!engine||result)return;const correct=option.key===question.answer.key;const ms=Math.round(performance.now()-startedAt.current);correct?SoundEngine.correct():SoundEngine.wrong();await engine.recordAnswer({surahNumber:question.current.surahNumber,ayahNumber:question.answer.ayahNumber,questionType:"next_ayah",correct,responseTimeMs:ms,metadata:{promptAyah:question.current.ayahNumber}});if(correct){const completed=await engine.complete({elapsedSeconds:Math.round(ms/1000)});SoundEngine.win();setResult(completed);}else setError("اقتربت. حاول اختيار الآية التي تأتي مباشرة بعدها.");}
  function reset(){setResult(null);setQuestion(null);setError("");setEngine(null);}
  if(viewer===undefined)return <div className="center"><i className="spinner"/><p>جارٍ تجهيز العجلة...</p></div>;
  return <QuranGameShell title="العجلة الدوارة" subtitle="تحديات من السور التي تدرسها"><section className="qgame-intro"><div><span>تحدي الاستدعاء</span><h1>لف العجلة واكتشف سؤالك</h1><p>{viewer?.teacherPreview?"معاينة كاملة للمعلم بلا تسجيل نقاط.":"العجلة تختار من السور التي بدأ الطفل دراستها، وإذا لم يبدأ بعد تستخدم سورًا قصيرة مناسبة."}</p></div><Difficulty value={difficulty} onChange={setDifficulty}/></section>{error&&<div className="msg error">{error}</div>}{result?<ResultPanel session={result} onAgain={reset}/>:<div className="wheel-layout"><section className="wheel-stage"><div className="wheel-pointer"><Icon name="target" size={28}/></div><div className={`quran-wheel ${spinning?"spinning":""}`} style={{transform:`rotate(${rotation}deg)`}}>{surahChoices.slice(0,8).map((n,i)=><span key={n} style={{transform:`rotate(${i*45}deg) translateY(-112px) rotate(${-i*45}deg)`}}>س{n}</span>)}</div><button className="primary wheel-button" disabled={spinning||!learningActorReady(viewer)} onClick={spin}>{spinning?"العجلة تدور...":"لف العجلة"}</button><small>الجولات: {round}</small></section><section className="wheel-question">{!question?<div className="qgame-placeholder"><Icon name="target" size={54}/><h2>جاهز للتحدي؟</h2><p>اضغط «لف العجلة» وستحصل على سؤال مختلف.</p></div>:<><span className="question-label">ما الآية التالية بعد هذه الآية؟</span><blockquote className="quran-text">{question.current.text}</blockquote><div className="ayah-option-list">{question.options.map(o=><button key={o.key} onClick={()=>answer(o)} disabled={!learningActorReady(viewer)}><b>الآية {o.ayahNumber}</b><span>{o.text}</span></button>)}</div></>}</section></div>}</QuranGameShell>;
}

function PointerSortable({items,setItems,disabled=false}){
  const drag=useRef(null);
  function down(e,index){if(disabled)return;drag.current=index;e.currentTarget.setPointerCapture?.(e.pointerId);e.currentTarget.classList.add("dragging");}
  function move(e){if(drag.current==null||disabled)return;const el=document.elementFromPoint(e.clientX,e.clientY)?.closest?.("[data-sort-index]");if(!el)return;const over=Number(el.dataset.sortIndex);if(Number.isNaN(over)||over===drag.current)return;setItems(prev=>{const next=[...prev];const [moved]=next.splice(drag.current,1);next.splice(over,0,moved);drag.current=over;return next;});}
  function up(e){drag.current=null;e.currentTarget.classList.remove("dragging");}
  function moveBy(index,dir){const to=index+dir;if(to<0||to>=items.length)return;setItems(prev=>{const next=[...prev];[next[index],next[to]]=[next[to],next[index]];return next;});}
  return <div className="sortable-ayahs">{items.map((item,index)=><article key={item.key} data-sort-index={index} onPointerDown={e=>down(e,index)} onPointerMove={move} onPointerUp={up} onPointerCancel={up}><span className="drag-handle"><Icon name="menu" size={20}/></span><div className="grow"><b>آية {item.ayahNumber}</b><p className="quran-text small">{item.text}</p></div><div className="sort-actions"><button onClick={()=>moveBy(index,-1)} disabled={index===0}>↑</button><button onClick={()=>moveBy(index,1)} disabled={index===items.length-1}>↓</button></div></article>)}</div>;
}

export function AyahOrderGame(){
  const runtime=useQuranGame("ayah-order"); const {viewer,surahChoices,difficulty,setDifficulty,error,setError}=runtime; const [surah,setSurah]=useState(null);const [correct,setCorrect]=useState([]);const [cards,setCards]=useState([]);const [engine,setEngine]=useState(null);const [result,setResult]=useState(null);const start=useRef(0);
  async function newRound(){setResult(null);setError("");const n=randomItem(surahChoices);const verses=await getSurahAyahs(n);const count=difficulty==="easy"?3:difficulty==="medium"?4:5;const begin=Math.max(0,Math.floor(Math.random()*Math.max(1,verses.length-count)));const selected=verses.slice(begin,begin+count);const eng=runtime.engine();await eng.start({difficulty,surahNumber:n,ayahNumbers:selected.map(v=>v.ayahNumber)});setSurah(n);setCorrect(selected);setCards(shuffle(selected));setEngine(eng);start.current=performance.now();}
  useEffect(()=>{if(viewer&&surahChoices.length&&!engine&&!result)newRound().catch(e=>setError(e.message));},[viewer,surahChoices.length,difficulty]);
  async function verify(){const ok=cards.every((c,i)=>c.key===correct[i]?.key);const ms=Math.round(performance.now()-start.current);for(const ayah of correct){await engine.recordAnswer({surahNumber:ayah.surahNumber,ayahNumber:ayah.ayahNumber,questionType:"ayah_order",correct:ok,responseTimeMs:ms,metadata:{range:correct.map(x=>x.ayahNumber)}});}if(!ok){SoundEngine.wrong();setError("الترتيب ليس صحيحًا بعد. حرّك البطاقات وحاول مرة أخرى.");return;}SoundEngine.correct();const done=await engine.complete({elapsedSeconds:Math.round(ms/1000)});SoundEngine.win();setResult(done);}
  if(viewer===undefined)return <div className="center"><i className="spinner"/><p>جارٍ تجهيز ترتيب الآيات...</p></div>;
  return <QuranGameShell title="ترتيب الآيات" subtitle="اسحب الآيات إلى ترتيبها الصحيح"><section className="qgame-intro"><div><span>سحب وإفلات</span><h1>{surah?`رتّب مقطعًا من سورة ${correct[0]?.surahName||""}`:"تجهيز المقطع"}</h1><p>اسحب البطاقة باللمس أو الماوس، ويمكنك استخدام الأسهم كبديل قابل للوصول.</p></div><Difficulty value={difficulty} onChange={v=>{setDifficulty(v);setEngine(null);setCards([]);setCorrect([]);}}/></section>{error&&<div className="msg error">{error}</div>}{result?<ResultPanel session={result} onAgain={()=>{setResult(null);setEngine(null);newRound().catch(e=>setError(e.message));}}/>:<section className="game-stage"><PointerSortable items={cards} setItems={setCards} disabled={!learningActorReady(viewer)}/><button className="primary full" disabled={!engine||!cards.length} onClick={verify}><Icon name="check" size={18}/> تحقق من الترتيب</button></section>}</QuranGameShell>;
}

function missingWordQuestion(verses,ayah){const words=ayah.words||[];const valid=words.filter((_,i)=>i>0&&i<words.length-1);const target=randomItem(valid.length?valid:words);const nearby=verses.flatMap(v=>v.words||[]).filter(w=>w.text!==target.text);const distractors=[...new Set(shuffle(nearby).map(w=>w.text))].slice(0,3);return {target,options:shuffle([target.text,...distractors]),before:words.filter(w=>w.position<target.position).map(w=>w.text).join(" "),after:words.filter(w=>w.position>target.position).map(w=>w.text).join(" ")};}

export function CompleteAyahGame(){
  const runtime=useQuranGame("complete-ayah");const {viewer,surahChoices,difficulty,setDifficulty,error,setError}=runtime;const [ayah,setAyah]=useState(null);const [q,setQ]=useState(null);const [engine,setEngine]=useState(null);const [result,setResult]=useState(null);const started=useRef(0);
  async function newRound(){setError("");setResult(null);const n=randomItem(surahChoices);const verses=await getSurahAyahs(n);const chosen=randomItem(verses.filter(v=>(v.words||[]).length>=4));const question=missingWordQuestion(verses,chosen);const eng=runtime.engine();await eng.start({difficulty,surahNumber:n,ayahNumbers:[chosen.ayahNumber]});setAyah(chosen);setQ(question);setEngine(eng);started.current=performance.now();}
  useEffect(()=>{if(viewer&&surahChoices.length&&!engine&&!result)newRound().catch(e=>setError(e.message));},[viewer,surahChoices.length,difficulty]);
  async function choose(value){const ok=value===q.target.text;const ms=Math.round(performance.now()-started.current);await engine.recordAnswer({surahNumber:ayah.surahNumber,ayahNumber:ayah.ayahNumber,questionType:"missing_word",correct:ok,responseTimeMs:ms,metadata:{wordPosition:q.target.position}});if(!ok){SoundEngine.wrong();setError("ليست الكلمة الصحيحة. اقرأ ما قبل الفراغ وما بعده وحاول مرة أخرى.");return;}SoundEngine.correct();const done=await engine.complete({elapsedSeconds:Math.round(ms/1000)});SoundEngine.win();setResult(done);}
  if(viewer===undefined)return <div className="center"><i className="spinner"/><p>جارٍ تجهيز إكمال الآية...</p></div>;
  return <QuranGameShell title="إكمال الآية" subtitle="الكلمة المرجعية من QuranData"><section className="qgame-intro"><div><span>استرجاع الكلمات</span><h1>ما الكلمة الناقصة؟</h1><p>النص المعروض مشتق مباشرة من الآية الأصلية؛ لا يتم تعديل النص المخزن.</p></div><Difficulty value={difficulty} onChange={v=>{setDifficulty(v);setEngine(null);}}/></section>{error&&<div className="msg error">{error}</div>}{result?<ResultPanel session={result} onAgain={()=>{setEngine(null);setResult(null);newRound().catch(e=>setError(e.message));}}/>:q&&<section className="game-stage missing-word-stage"><div className="quran-text missing-ayah"><span>{q.before}</span><mark>ــــــــــــ</mark><span>{q.after}</span></div><div className="word-options">{q.options.map(word=><button key={word} onClick={()=>choose(word)}>{word}</button>)}</div></section>}</QuranGameShell>;
}

export function QuickMemoryGame(){
  const runtime=useQuranGame("quick-memory");const {viewer,surahChoices,difficulty,setDifficulty,error,setError}=runtime;const [phase,setPhase]=useState("loading");const [ayah,setAyah]=useState(null);const [q,setQ]=useState(null);const [seconds,setSeconds]=useState(0);const [engine,setEngine]=useState(null);const [result,setResult]=useState(null);const answerStart=useRef(0);const timerRef=useRef(null);
  async function newRound(){clearInterval(timerRef.current);setResult(null);setError("");const n=randomItem(surahChoices);const verses=await getSurahAyahs(n);const chosen=randomItem(verses.filter(v=>(v.words||[]).length>=5));const eng=runtime.engine();await eng.start({difficulty,surahNumber:n,ayahNumbers:[chosen.ayahNumber]});setAyah(chosen);setQ(missingWordQuestion(verses,chosen));setEngine(eng);const watch=difficulty==="hard"?5:difficulty==="medium"?7:10;setSeconds(watch);setPhase("watch");timerRef.current=setInterval(()=>setSeconds(s=>{if(s<=1){clearInterval(timerRef.current);setPhase("answer");answerStart.current=performance.now();return 0;}SoundEngine.tick();return s-1;}),1000);}
  useEffect(()=>{if(viewer&&surahChoices.length&&!engine&&!result)newRound().catch(e=>setError(e.message));return()=>clearInterval(timerRef.current);},[viewer,surahChoices.length,difficulty]);
  async function choose(value){const ok=value===q.target.text;const ms=Math.round(performance.now()-answerStart.current);await engine.recordAnswer({surahNumber:ayah.surahNumber,ayahNumber:ayah.ayahNumber,questionType:"quick_memory_missing_word",correct:ok,responseTimeMs:ms,metadata:{wordPosition:q.target.position}});if(!ok){SoundEngine.wrong();setError("جرّب مرة أخرى. تذكّر شكل الآية الذي ظهر قبل قليل.");return;}SoundEngine.correct();const done=await engine.complete({elapsedSeconds:Math.round(ms/1000)});SoundEngine.win();setResult(done);}
  if(viewer===undefined)return <div className="center"><i className="spinner"/><p>جارٍ تجهيز الذاكرة السريعة...</p></div>;
  return <QuranGameShell title="الذاكرة السريعة" subtitle="انظر، احفظ، ثم استرجع"><section className="qgame-intro"><div><span>تدريب الذاكرة</span><h1>{phase==="watch"?`احفظ الآية خلال ${seconds} ثوانٍ`:"استرجع الكلمة الناقصة"}</h1><p>كلما ارتفع المستوى يقل وقت المشاهدة، لكن الأداء القرآني يظل العامل الأساسي في النجوم.</p></div><Difficulty value={difficulty} onChange={v=>{setDifficulty(v);setEngine(null);}}/></section>{error&&<div className="msg error">{error}</div>}{result?<ResultPanel session={result} onAgain={()=>{setEngine(null);setResult(null);newRound().catch(e=>setError(e.message));}}/>:<section className="game-stage quick-memory-stage">{phase==="watch"&&ayah?<><div className="memory-countdown">{seconds}</div><blockquote className="quran-text memory-verse">{ayah.text}</blockquote><div className="game-progress"><i style={{width:`${clamp(seconds/(difficulty==="hard"?5:difficulty==="medium"?7:10)*100,0,100)}%`}}/></div></>:phase==="answer"&&q?<><div className="quran-text missing-ayah"><span>{q.before}</span><mark>ــــــــــــ</mark><span>{q.after}</span></div><div className="word-options">{q.options.map(word=><button key={word} onClick={()=>choose(word)}>{word}</button>)}</div></>:<div className="center"><i className="spinner"/></div>}</section>}</QuranGameShell>;
}
