import React, { useEffect, useRef, useState } from "react";
import Icon from "./Icon.jsx";
import { getProgress } from "./api.js";
import { loadLearningViewer, learningActorReady } from "./learningViewer.js";
import { getSurahAyahs, loadQuranData, splitAyahIntoChunks } from "./quranCorpus.js";
import { GameEngine, gameResultSummary } from "./gameEngine.js";
import { SoundEngine } from "./soundEngine.js";

const SAFE_SHORT_SURAHS=[112,113,114,108,109,110,111,103,104,105,106,107,67];
function routePath(){return typeof window.__ABU_ROUTE_PATH__==="function"?window.__ABU_ROUTE_PATH__():window.location.pathname;}
function navigate(path){if(routePath()!==path){history.pushState({},"",path);window.dispatchEvent(new PopStateEvent("popstate"));}}
function shuffle(items){const next=[...items];for(let i=next.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[next[i],next[j]]=[next[j],next[i]];}return next;}
function randomItem(items){return items[Math.floor(Math.random()*items.length)];}
function sameOrder(a,b){return a.length===b.length&&a.every((x,i)=>x.id===b[i]?.id);}
function shuffledDifferent(items){if(items.length<2)return [...items];let next=shuffle(items);if(sameOrder(next,items))next=[...next.slice(1),next[0]];return next;}

function useRuntime(gameId){
  const [viewer,setViewer]=useState(undefined);const [quran,setQuran]=useState(null);const [surahChoices,setSurahChoices]=useState([]);const [difficulty,setDifficulty]=useState("easy");const [error,setError]=useState("");
  useEffect(()=>{let alive=true;(async()=>{try{const context=await loadLearningViewer();if(!alive)return;if(!context.user)return navigate("/login");const data=await loadQuranData();if(!alive)return;let choices=SAFE_SHORT_SURAHS;if(!context.teacherPreview&&context.child?.id){const progress=await getProgress(context.child.id);const studied=(progress||[]).filter(p=>Number(p.memorized_percent||0)>0).map(p=>Number(p.surah_number));if(studied.length)choices=[...new Set(studied)];}setViewer(context);setQuran(data);setSurahChoices(choices.filter(n=>data.surahs.some(s=>s.number===n)));}catch(e){if(alive)setError(e.message||"تعذر تجهيز اللعبة.");}})();return()=>{alive=false;};},[gameId]);
  const makeEngine=()=>new GameEngine({childId:viewer?.child?.id,gameId,teacherPreview:Boolean(viewer?.teacherPreview)});
  return {viewer,quran,surahChoices,difficulty,setDifficulty,error,setError,makeEngine};
}

function Difficulty({value,onChange}){return <div className="difficulty-tabs">{[["easy","سهل"],["medium","متوسط"],["hard","متقدم"]].map(([v,label])=><button key={v} className={value===v?"active":""} onClick={()=>onChange(v)}>{label}</button>)}</div>;}
function GameHeader({title,subtitle}){const [sound,setSound]=useState(SoundEngine.isEnabled());return <header className="game-topbar"><div className="wrap nav"><button className="brand" onClick={()=>navigate("/games")}><span className="logo"><Icon name="game" size={22}/></span><span><b>{title}</b><small>{subtitle}</small></span></button><div className="actions"><button className="secondary" onClick={()=>{SoundEngine.setEnabled(!sound);setSound(!sound);}}><Icon name={sound?"sound":"mute"} size={17}/>{sound?"الصوت يعمل":"الصوت متوقف"}</button><button className="secondary" onClick={()=>navigate("/games")}><Icon name="arrow" size={17}/> عالم الألعاب</button></div></div></header>;}
function Shell({title,subtitle,children}){return <div className="app quran-game-system quran-game-batch2" dir="rtl"><GameHeader title={title} subtitle={subtitle}/><main className="wrap page qgame-page">{children}</main><footer><div className="wrap">كل نص قرآني في هذه اللعبة يُقرأ من QuranData الموثق بمصدر Tanzil، ولا يُكتب يدويًا داخل اللعبة.</div></footer></div>;}
function Stars({count=0}){return <div className="result-stars">{[1,2,3].map(n=><span key={n} className={n<=count?"earned":""}><Icon name="star" size={28}/></span>)}</div>;}
function Result({session,onAgain}){const r=gameResultSummary(session);if(!r)return null;return <section className="qgame-result"><span className="qgame-result-icon"><Icon name="trophy" size={42}/></span><h2>أحسنت، اكتملت الجولة</h2><Stars count={r.stars}/><div className="qgame-result-stats"><div><b>{r.score}</b><small>نقطة</small></div><div><b>{r.accuracy}%</b><small>دقة</small></div><div><b>{r.correct}</b><small>صحيح</small></div><div><b>{r.wrong}</b><small>محاولة خاطئة</small></div></div><div className="row" style={{justifyContent:"center"}}><button className="secondary" onClick={()=>navigate("/games")}>عالم الألعاب</button><button className="primary" onClick={onAgain}>جولة جديدة</button></div></section>;}

function SortablePieces({items,setItems,disabled=false,className=""}){
  const drag=useRef(null);
  function down(e,index){if(disabled)return;drag.current=index;e.currentTarget.setPointerCapture?.(e.pointerId);e.currentTarget.classList.add("dragging");}
  function move(e){if(drag.current==null||disabled)return;const el=document.elementFromPoint(e.clientX,e.clientY)?.closest?.("[data-piece-index]");if(!el)return;const over=Number(el.dataset.pieceIndex);if(Number.isNaN(over)||over===drag.current)return;setItems(prev=>{const next=[...prev];const [moved]=next.splice(drag.current,1);next.splice(over,0,moved);drag.current=over;return next;});}
  function up(e){drag.current=null;e.currentTarget.classList.remove("dragging");}
  function shift(index,dir){const to=index+dir;if(to<0||to>=items.length)return;setItems(prev=>{const next=[...prev];[next[index],next[to]]=[next[to],next[index]];return next;});SoundEngine.tap();}
  return <div className={`batch-sortable ${className}`}>{items.map((item,index)=><article key={item.id} data-piece-index={index} onPointerDown={e=>down(e,index)} onPointerMove={move} onPointerUp={up} onPointerCancel={up}><span className="piece-handle"><Icon name="menu" size={18}/></span><b>{item.text}</b><div className="piece-actions"><button onClick={()=>shift(index,-1)} disabled={index===0||disabled}>→</button><button onClick={()=>shift(index,1)} disabled={index===items.length-1||disabled}>←</button></div></article>)}</div>;
}

function pickAyah(verses,minWords=4,maxWords=18){const candidates=verses.filter(v=>(v.words?.length||0)>=minWords&&(v.words?.length||0)<=maxWords);return randomItem(candidates.length?candidates:verses.filter(v=>(v.words?.length||0)>=minWords));}

export function WordTrainGame(){
  const runtime=useRuntime("word-train");const {viewer,surahChoices,difficulty,setDifficulty,error,setError}=runtime;const [ayah,setAyah]=useState(null);const [pieces,setPieces]=useState([]);const [engine,setEngine]=useState(null);const [result,setResult]=useState(null);const started=useRef(0);
  async function newRound(){setResult(null);setError("");const surah=randomItem(surahChoices);const verses=await getSurahAyahs(surah);const chosen=pickAyah(verses,difficulty==="easy"?4:6,difficulty==="easy"?10:16);if(!chosen)throw new Error("لا توجد آية مناسبة لهذا المستوى في السورة المختارة.");const words=chosen.words.map(w=>({id:`${chosen.key}:${w.position}`,text:w.text,position:w.position}));const eng=runtime.makeEngine();await eng.start({difficulty,surahNumber:surah,ayahNumbers:[chosen.ayahNumber]});setAyah(chosen);setPieces(shuffledDifferent(words));setEngine(eng);started.current=performance.now();}
  useEffect(()=>{if(viewer&&surahChoices.length&&!engine&&!result)newRound().catch(e=>setError(e.message));},[viewer,surahChoices.length,difficulty]);
  async function verify(){if(!ayah||!engine)return;const ok=pieces.every((p,i)=>p.position===i+1);const ms=Math.round(performance.now()-started.current);await engine.recordAnswer({surahNumber:ayah.surahNumber,ayahNumber:ayah.ayahNumber,questionType:"word_order",correct:ok,responseTimeMs:ms,metadata:{submittedOrder:pieces.map(p=>p.position)}});if(!ok){SoundEngine.wrong();setError("القطار لم يتحرك بعد. رتّب الكلمات مرة أخرى وحاول.");return;}SoundEngine.correct();const done=await engine.complete({elapsedSeconds:Math.round(ms/1000)});SoundEngine.win();setResult(done);}
  if(viewer===undefined)return <div className="center"><i className="spinner"/><p>جارٍ تجهيز القطار...</p></div>;
  return <Shell title="قطار الكلمات" subtitle="رتّب عربات الآية"><section className="qgame-intro"><div><span>محطة الكلمات</span><h1>{ayah?`سورة ${ayah.surahName} — آية ${ayah.ayahNumber}`:"تجهيز الرحلة"}</h1><p>حرّك عربات الكلمات حتى تصبح الآية بالترتيب الصحيح، ثم شغّل القطار.</p></div><Difficulty value={difficulty} onChange={v=>{setDifficulty(v);setEngine(null);setAyah(null);setPieces([]);}}/></section>{error&&<div className="msg error">{error}</div>}{result?<Result session={result} onAgain={()=>{setEngine(null);setAyah(null);setPieces([]);setResult(null);}}/>:<section className="game-stage train-stage"><div className="train-track" aria-hidden="true"><span className="train-engine"><Icon name="bolt" size={26}/></span><i/><i/><i/></div><SortablePieces items={pieces} setItems={setPieces} disabled={!learningActorReady(viewer)} className="train-pieces"/><button className="primary full" disabled={!engine||!pieces.length} onClick={verify}><Icon name="check" size={18}/> شغّل القطار وتحقق</button></section>}</Shell>;
}

export function AyahBurgerGame(){
  const runtime=useRuntime("ayah-burger");const {viewer,surahChoices,difficulty,setDifficulty,error,setError}=runtime;const [ayah,setAyah]=useState(null);const [pieces,setPieces]=useState([]);const [engine,setEngine]=useState(null);const [result,setResult]=useState(null);const started=useRef(0);
  async function newRound(){setResult(null);setError("");const surah=randomItem(surahChoices);const verses=await getSurahAyahs(surah);const chosen=pickAyah(verses,6,22);if(!chosen)throw new Error("لا توجد آية مناسبة لبناء البرجر في السورة المختارة.");const chunks=splitAyahIntoChunks(chosen,difficulty==="easy"?3:difficulty==="medium"?4:5).map((c,i)=>({id:`${chosen.key}:chunk:${i}`,text:c.text,order:i+1}));const eng=runtime.makeEngine();await eng.start({difficulty,surahNumber:surah,ayahNumbers:[chosen.ayahNumber]});setAyah(chosen);setPieces(shuffledDifferent(chunks));setEngine(eng);started.current=performance.now();}
  useEffect(()=>{if(viewer&&surahChoices.length&&!engine&&!result)newRound().catch(e=>setError(e.message));},[viewer,surahChoices.length,difficulty]);
  async function verify(){if(!ayah||!engine)return;const ok=pieces.every((p,i)=>p.order===i+1);const ms=Math.round(performance.now()-started.current);await engine.recordAnswer({surahNumber:ayah.surahNumber,ayahNumber:ayah.ayahNumber,questionType:"chunk_order",correct:ok,responseTimeMs:ms,metadata:{chunkOrder:pieces.map(p=>p.order)}});if(!ok){SoundEngine.wrong();setError("الطبقات ليست بالترتيب الصحيح. أعد ترتيب أجزاء الآية.");return;}SoundEngine.correct();const done=await engine.complete({elapsedSeconds:Math.round(ms/1000)});SoundEngine.win();setResult(done);}
  if(viewer===undefined)return <div className="center"><i className="spinner"/><p>جارٍ تجهيز المطبخ...</p></div>;
  return <Shell title="صانع البرجر" subtitle="ابنِ الآية طبقة فوق طبقة"><section className="qgame-intro"><div><span>مطبخ الآيات</span><h1>{ayah?`ابنِ آية ${ayah.ayahNumber} من سورة ${ayah.surahName}`:"تجهيز المكونات"}</h1><p>كل طبقة هي جزء حقيقي من الآية. رتبها من البداية للنهاية.</p></div><Difficulty value={difficulty} onChange={v=>{setDifficulty(v);setEngine(null);setAyah(null);setPieces([]);}}/></section>{error&&<div className="msg error">{error}</div>}{result?<Result session={result} onAgain={()=>{setEngine(null);setAyah(null);setPieces([]);setResult(null);}}/>:<section className="game-stage burger-stage"><div className="burger-cap top" aria-hidden="true"/><SortablePieces items={pieces} setItems={setPieces} disabled={!learningActorReady(viewer)} className="burger-pieces"/><div className="burger-cap bottom" aria-hidden="true"/><button className="primary full" disabled={!engine||!pieces.length} onClick={verify}><Icon name="check" size={18}/> قدّم البرجر وتحقق</button></section>}</Shell>;
}

function makeMissingWordQuestion(ayah,verses,difficulty){const words=ayah.words||[];const candidates=words.map((w,i)=>({w,i})).filter(x=>x.i>0&&x.i<words.length-1);if(!candidates.length)return null;const target=randomItem(candidates);const pool=shuffle(verses.flatMap(v=>v.words||[]).filter(w=>w.text!==target.w.text)).slice(0,difficulty==="easy"?3:2);return {type:"missing_word",ayah,prompt:words.map((w,i)=>i===target.i?"ــــــ":w.text).join(" "),answer:target.w.text,options:shuffle([target.w.text,...pool.map(w=>w.text)])};}
function makeNextAyahQuestion(verses,difficulty){if(verses.length<2)return null;const current=verses[Math.floor(Math.random()*(verses.length-1))];const answer=verses[current.ayahNumber];const nearby=verses.filter(v=>v.key!==answer.key&&v.key!==current.key);return {type:"next_ayah",ayah:answer,prompt:current.text,answer:answer.key,options:shuffle([answer,...shuffle(nearby).slice(0,difficulty==="easy"?3:2)]).map(v=>({value:v.key,label:v.text,ayahNumber:v.ayahNumber}))};}

export function KnowledgeBridgeGame(){
  const runtime=useRuntime("knowledge-bridge");const {viewer,surahChoices,difficulty,setDifficulty,error,setError}=runtime;const [questions,setQuestions]=useState([]);const [index,setIndex]=useState(0);const [engine,setEngine]=useState(null);const [result,setResult]=useState(null);const sessionStart=useRef(0);const questionStart=useRef(0);
  async function newRound(){setResult(null);setError("");const surah=randomItem(surahChoices);const verses=await getSurahAyahs(surah);const total=difficulty==="easy"?4:difficulty==="medium"?5:6;const built=[];for(let i=0;i<total;i++){const q=i%2===0?makeNextAyahQuestion(verses,difficulty):makeMissingWordQuestion(pickAyah(verses,4,18),verses,difficulty);if(q)built.push(q);}if(built.length<3)throw new Error("السورة المختارة لا تكفي لبناء أسئلة الجسر.");const eng=runtime.makeEngine();await eng.start({difficulty,surahNumber:surah,ayahNumbers:[...new Set(built.map(q=>q.ayah.ayahNumber))]});setQuestions(built);setIndex(0);setEngine(eng);sessionStart.current=performance.now();questionStart.current=performance.now();}
  useEffect(()=>{if(viewer&&surahChoices.length&&!engine&&!result)newRound().catch(e=>setError(e.message));},[viewer,surahChoices.length,difficulty]);
  const q=questions[index]||null;
  async function answer(value){if(!q||!engine)return;const correct=value===q.answer;const ms=Math.round(performance.now()-questionStart.current);await engine.recordAnswer({surahNumber:q.ayah.surahNumber,ayahNumber:q.ayah.ayahNumber,questionType:q.type,correct,responseTimeMs:ms,metadata:{question:index+1}});if(!correct){SoundEngine.wrong();setError("الإجابة ليست صحيحة. الجسر ينتظر قطعة صحيحة قبل أن تكمل.");questionStart.current=performance.now();return;}SoundEngine.correct();setError("");if(index>=questions.length-1){const elapsed=Math.round((performance.now()-sessionStart.current)/1000);const done=await engine.complete({elapsedSeconds:elapsed});SoundEngine.win();setResult(done);return;}setIndex(i=>i+1);questionStart.current=performance.now();}
  if(viewer===undefined)return <div className="center"><i className="spinner"/><p>جارٍ تجهيز الجسر...</p></div>;
  return <Shell title="جسر المعرفة" subtitle="كل إجابة تبني خطوة"><section className="qgame-intro"><div><span>رحلة الاسترجاع</span><h1>اعبر النهر بإجاباتك</h1><p>كل إجابة صحيحة تضيف لوحًا جديدًا إلى الجسر. الخطأ لا ينهي الجولة لكنه يدخل الآية في المراجعة الذكية.</p></div><Difficulty value={difficulty} onChange={v=>{setDifficulty(v);setEngine(null);setQuestions([]);setIndex(0);}}/></section>{error&&<div className="msg error">{error}</div>}{result?<Result session={result} onAgain={()=>{setEngine(null);setQuestions([]);setResult(null);setIndex(0);}}/>:<section className="game-stage bridge-stage"><div className="bridge-visual" aria-hidden="true"><span className="river">≈≈≈≈≈≈≈≈≈</span><div className="bridge-planks">{questions.map((_,i)=><i key={i} className={i<index?"built":i===index?"current":""}/>)}</div></div>{q&&<div className="bridge-question"><span className="question-label">{q.type==="next_ayah"?"ما الآية التالية؟":"ما الكلمة الناقصة؟"}</span><blockquote className="quran-text">{q.prompt}</blockquote><div className="ayah-option-list">{q.type==="next_ayah"?q.options.map(o=><button key={o.value} onClick={()=>answer(o.value)}><b>آية {o.ayahNumber}</b><span>{o.label}</span></button>):q.options.map(o=><button key={o} onClick={()=>answer(o)}><span className="word-choice">{o}</span></button>)}</div><small>خطوة {index+1} من {questions.length}</small></div>}</section>}</Shell>;
}

function uniquePairAyahs(verses,count){const selected=[];const seenBeg=new Set(),seenEnd=new Set();for(const v of shuffle(verses.filter(x=>(x.words?.length||0)>=6))){const beg=v.words.slice(0,3).map(w=>w.text).join(" ");const end=v.words.slice(-3).map(w=>w.text).join(" ");if(seenBeg.has(beg)||seenEnd.has(end))continue;seenBeg.add(beg);seenEnd.add(end);selected.push(v);if(selected.length===count)break;}return selected;}

export function FlipCardsGame(){
  const runtime=useRuntime("flip-cards");const {viewer,surahChoices,difficulty,setDifficulty,error,setError}=runtime;const [cards,setCards]=useState([]);const [flipped,setFlipped]=useState([]);const [matched,setMatched]=useState([]);const [engine,setEngine]=useState(null);const [result,setResult]=useState(null);const start=useRef(0);const locked=useRef(false);
  async function newRound(){setResult(null);setError("");setFlipped([]);setMatched([]);const surah=randomItem(surahChoices);const verses=await getSurahAyahs(surah);const pairCount=difficulty==="easy"?3:difficulty==="medium"?4:5;const selected=uniquePairAyahs(verses,pairCount);if(selected.length<3)throw new Error("لا توجد آيات كافية لتكوين بطاقات مختلفة في السورة المختارة.");const deck=shuffle(selected.flatMap(v=>[{id:`b:${v.key}`,pair:v.key,kind:"begin",text:v.words.slice(0,3).map(w=>w.text).join(" "),ayah:v},{id:`e:${v.key}`,pair:v.key,kind:"end",text:v.words.slice(-3).map(w=>w.text).join(" "),ayah:v}]));const eng=runtime.makeEngine();await eng.start({difficulty,surahNumber:surah,ayahNumbers:selected.map(v=>v.ayahNumber)});setCards(deck);setEngine(eng);start.current=performance.now();}
  useEffect(()=>{if(viewer&&surahChoices.length&&!engine&&!result)newRound().catch(e=>setError(e.message));},[viewer,surahChoices.length,difficulty]);
  async function flip(card){if(locked.current||matched.includes(card.pair)||flipped.some(x=>x.id===card.id))return;SoundEngine.tap();const next=[...flipped,card];setFlipped(next);if(next.length<2)return;locked.current=true;const [a,b]=next;const same=a.pair===b.pair&&a.kind!==b.kind;const ms=Math.round(performance.now()-start.current);if(same){await engine.recordAnswer({surahNumber:a.ayah.surahNumber,ayahNumber:a.ayah.ayahNumber,questionType:"matching",correct:true,responseTimeMs:ms,metadata:{pair:a.pair}});SoundEngine.correct();const nextMatched=[...matched,a.pair];setMatched(nextMatched);setFlipped([]);locked.current=false;if(nextMatched.length*2===cards.length){const done=await engine.complete({elapsedSeconds:Math.round(ms/1000)});SoundEngine.win();setResult(done);}return;}await Promise.all([a,b].map(x=>engine.recordAnswer({surahNumber:x.ayah.surahNumber,ayahNumber:x.ayah.ayahNumber,questionType:"matching",correct:false,responseTimeMs:ms,metadata:{pairedWith:x.id===a.id?b.pair:a.pair}})));SoundEngine.wrong();setError("ليستا بداية ونهاية للآية نفسها. تذكّر موضعهما وحاول من جديد.");setTimeout(()=>{setFlipped([]);locked.current=false;},700);}
  if(viewer===undefined)return <div className="center"><i className="spinner"/><p>جارٍ تجهيز البطاقات...</p></div>;
  return <Shell title="البطاقات المقلوبة" subtitle="طابق بداية الآية بنهايتها"><section className="qgame-intro"><div><span>ذاكرة وربط</span><h1>اكشف البطاقات واصنع الأزواج</h1><p>كل زوج صحيح يربط بداية الآية بنهايتها من نفس النص المرجعي.</p></div><Difficulty value={difficulty} onChange={v=>{setDifficulty(v);setEngine(null);setCards([]);setFlipped([]);setMatched([]);}}/></section>{error&&<div className="msg error">{error}</div>}{result?<Result session={result} onAgain={()=>{setEngine(null);setCards([]);setResult(null);setFlipped([]);setMatched([]);}}/>:<section className="game-stage flip-stage"><div className="flip-grid">{cards.map(card=>{const open=flipped.some(x=>x.id===card.id)||matched.includes(card.pair);return <button key={card.id} className={`flip-qcard ${open?"open":""} ${matched.includes(card.pair)?"matched":""}`} disabled={!learningActorReady(viewer)} onClick={()=>flip(card)}><span className="flip-back"><Icon name="quran" size={30}/><small>اكشف</small></span><span className="flip-front"><small>{card.kind==="begin"?"بداية":"نهاية"}</small><b>{card.text}</b></span></button>;})}</div><div className="flip-progress"><span>{matched.length} / {Math.floor(cards.length/2)} أزواج</span></div></section>}</Shell>;
}
