import React, { useEffect, useState } from "react";
import Icon from "./Icon.jsx";
import { claimReward, dayKey, getProgress, getCurrentUser, getActiveChildId, listChildren, recordReview } from "./api.js";
import { getSurah } from "./quranData.js";

function routePath(){return typeof window.__ABU_ROUTE_PATH__==="function"?window.__ABU_ROUTE_PATH__():window.location.pathname;}
function navigate(path){if(routePath()!==path){history.pushState({},"",path);window.dispatchEvent(new PopStateEvent("popstate"));}}

export default function ReviewPage(){
  const [user,setUser]=useState(undefined);const [child,setChild]=useState(null);const [progress,setProgress]=useState([]);const [msg,setMsg]=useState("");const [err,setErr]=useState("");const [busy,setBusy]=useState(false);
  async function load(current=user,selected=child){if(!current)return;const kids=await listChildren(current);const active=selected||kids.find(k=>k.id===getActiveChildId())||kids[0]||null;setChild(active);if(active)setProgress(await getProgress(active.id));}
  useEffect(()=>{let alive=true;(async()=>{try{const current=await getCurrentUser();if(!alive)return;if(!current)return navigate("/login");if(current.accountType==="teacher")return;setUser(current);const kids=await listChildren(current);const selected=kids.find(k=>k.id===getActiveChildId())||kids[0]||null;if(!alive)return;setChild(selected);if(selected)setProgress(await getProgress(selected.id));}catch(e){if(alive)setErr(e.message||"تعذر تحميل المراجعة.");}})();return()=>{alive=false;};},[]);
  async function rate(row,score){if(!user||!child)return;setBusy(true);setErr("");setMsg("");try{await recordReview(user,child.id,row.surah_number,score);await claimReward(child.id,"review_session",dayKey("review",row.surah_number)).catch(()=>{});setMsg(`تم تسجيل مراجعة سورة ${getSurah(row.surah_number)?.name||row.surah_name||row.surah_number}.`);await load(user,child);}catch(e){setErr(e.message||"تعذر تسجيل المراجعة.");}finally{setBusy(false);}}
  if(user===undefined)return <div className="center"><i className="spinner"/><p>جارٍ تجهيز المراجعة...</p></div>;
  const items=progress.filter(x=>Number(x.memorized_percent||0)>0);
  return <div className="app review-v2" dir="rtl"><header className="review-topbar"><div className="wrap nav"><button className="brand" onClick={()=>navigate("/")}><span className="logo"><Icon name="review" size={22}/></span><span><b>المراجعة</b><small>تثبيت الحفظ</small></span></button><div className="actions"><button className="secondary" onClick={()=>navigate("/child")}><Icon name="child" size={17}/> وضع الطفل</button><button className="secondary" onClick={()=>navigate("/quran")}><Icon name="quran" size={17}/> القرآن</button></div></div></header><main className="wrap page review-page"><section className="review-hero"><div><span className="review-kicker"><Icon name="review" size={18}/> راجع وثبّت</span><h1>مراجعة {child?.display_name||"الطفل"}</h1><p>اختر السورة وسجّل مستوى التسميع. تتحدث حالة المراجعة مباشرة في ملف الطفل.</p></div><div className="review-hero-art"><Icon name="quran" size={68}/></div></section>{err&&<div className="msg error">{err}</div>}{msg&&<div className="msg ok">{msg}</div>}{items.length?<div className="review-grid-v2">{items.map(row=>{const s=getSurah(row.surah_number);const review=Number(row.review_percent||0);return <article className="review-card-v2" key={row.surah_number}><div className="review-card-head"><span className="surah-mark"><Icon name="quran" size={25}/></span><div className="grow"><small>سورة</small><h2>{s?.name||row.surah_name||row.surah_number}</h2></div><strong>{review}%</strong></div><div className="bar big"><i style={{width:`${review}%`}}/></div><p>{review>=85?"مراجعة قوية — استمر على نفس المستوى.":review>0?"السورة تحتاج تثبيتًا إضافيًا.":"لم تُسجل مراجعة بعد."}</p><div className="review-score-buttons">{[[60,"يحتاج تدريب"],[80,"جيد"],[90,"ممتاز جدًا"],[100,"ممتاز"]].map(([score,label])=><button key={score} disabled={busy} className={review===score?"primary":"secondary"} onClick={()=>rate(row,score)}><Icon name={score>=90?"check":"target"} size={16}/>{label}</button>)}</div></article>;})}</div>:<section className="review-empty"><span><Icon name="quran" size={52}/></span><h2>ابدأ الحفظ أولًا</h2><p>ستظهر هنا السور التي بدأ الطفل حفظها حتى تستطيع مراجعتها وتقييمها.</p><button className="primary" onClick={()=>navigate("/memorize")}><Icon name="star" size={18}/> ابدأ جلسة حفظ</button></section>}</main><footer><div className="wrap">أبو العزايم للحفظ الممتع • المراجعة المنتظمة تثبّت الحفظ.</div></footer></div>;
}
