import React,{useEffect,useMemo,useState} from "react";
import {getActiveChildId,getCurrentUser,getProgress,listAchievements,listChildren} from "./api.js";
import {GameEngine} from "./gameEngine.js";
import {gameDefinition} from "./gameRegistry.js";
import {getSurah} from "./surahCatalog.js";
import {isChildModeActive} from "./ChildHub.jsx";
import {AppShell,Button,Card,CHILD_NAV,FAMILY_NAV,Hero,Metric,ProgressBar,Section,go} from "./ui-v4.jsx";

export default function RoomPage(){
  const [user,setUser]=useState(undefined),[child,setChild]=useState(null),[progress,setProgress]=useState([]),[achievements,setAchievements]=useState([]),[gameProgress,setGameProgress]=useState([]),[reviewQueue,setReviewQueue]=useState([]),[err,setErr]=useState("");
  useEffect(()=>{let alive=true;(async()=>{try{const current=await getCurrentUser();if(!alive)return;if(!current)return go("/login");if(current.accountType==="teacher")return;setUser(current);const kids=await listChildren(current);const selected=kids.find(k=>k.id===getActiveChildId())||kids[0]||null;if(!alive)return;setChild(selected);if(selected){const [rows,badges,games,due]=await Promise.all([getProgress(selected.id),listAchievements(selected.id),GameEngine.progress(selected.id),GameEngine.dueReview(selected.id,12)]);if(alive){setProgress(rows||[]);setAchievements(badges||[]);setGameProgress(games||[]);setReviewQueue(due||[]);}}}catch(e){if(alive)setErr(e.message||"تعذر تحميل غرفة الطفل.");}})();return()=>{alive=false;};},[]);
  if(user===undefined)return <div className="center"><i className="spinner"/><p>جارٍ تجهيز الغرفة...</p></div>;
  const avg=useMemo(()=>progress.length?Math.round(progress.reduce((s,r)=>s+Number(r.memorized_percent||0),0)/progress.length):0,[progress]);const mastered=progress.filter(r=>r.status==="mastered").length;const gamesMastered=gameProgress.filter(g=>Number(g.best_stars||0)>=3).length;const weakBySurah=useMemo(()=>{const m=new Map();for(const item of reviewQueue){if(!m.has(item.surah_number))m.set(item.surah_number,[]);m.get(item.surah_number).push(item);}return [...m.entries()].slice(0,4);},[reviewQueue]);const childMode=isChildModeActive();
  return <AppShell mode={childMode?"child":"family"} subtitle="غرفتي" nav={childMode?CHILD_NAV:FAMILY_NAV} footer="أبو العزايم • كل تقدمك في مكان واحد.">
    <Hero eyebrow="مساحتي" title={`غرفة ${child?.display_name||"بطلنا"}`} description={reviewQueue.length?`عندك ${reviewQueue.length} آية محتاجة مراجعة ذكية. نقدر نثبتهم بالمراجعة أو اللعب.`:"كل تقدمك ونقاطك ونجومك هنا من غير زحمة."} icon="room" tone="pink" aside={<div className="aa-child-score"><span>🔥 {child?.streak||0} يوم</span></div>}/>
    {err&&<div className="msg error">{err}</div>}
    <div className="aa-metrics"><Metric icon="trophy" label="نقطة" value={child?.points||0} tone="gold"/><Metric icon="star" label="نجمة" value={child?.stars||0} tone="sky"/><Metric icon="game" label="ألعاب متقنة" value={gamesMastered} tone="lavender"/><Metric icon="review" label="آيات للمراجعة" value={reviewQueue.length} tone="mint"/></div>
    <Section eyebrow="رحلتي" title="التقدم العام"><div className="aa-room-grid"><Card icon="quran" title="الحفظ" text={progress.length?`بدأت ${progress.length} سورة وأتقنت ${mastered} منها.`:"ابدأ أول جلسة حفظ علشان يظهر تقدمك هنا."} tone="sky"><div style={{marginTop:14}}><ProgressBar value={avg} label="متوسط الحفظ"/></div><div style={{marginTop:14}}><Button kind="soft" icon="quran" onClick={()=>go("/quran")}>القرآن</Button></div></Card><Card icon="trophy" title="الإنجازات" text={achievements.length?`فتحت ${achievements.length} ميدالية لحد دلوقتي.`:"لسه هنفتح أول ميدالية مع أول إنجاز."} tone="gold"><div style={{marginTop:14}}><Button kind="soft" icon="trophy" onClick={()=>go("/achievements")}>شوف الجوائز</Button></div></Card></div></Section>
    <Section eyebrow="المراجعة الذكية" title="نقاط تحتاج تثبيت"><div className="aa-room-grid"><article className="aa-card">{weakBySurah.length?<div className="aa-room-list">{weakBySurah.map(([surah,items])=><article key={surah}><span>📖</span><div><b>سورة {getSurah(surah)?.name||surah}</b><small>الآيات: {items.map(x=>x.ayah_number).join("، ")}</small></div><strong>{Math.max(...items.map(x=>x.priority))}</strong></article>)}</div>:<p style={{color:"var(--aa-muted)",margin:0}}>لا توجد آيات مستحقة للمراجعة الذكية الآن.</p>}<div style={{marginTop:14}}><Button kind="secondary" icon="review" onClick={()=>go("/review")}>ابدأ المراجعة</Button></div></article><article className="aa-card"><h3 style={{marginTop:0}}>إتقاني في الألعاب</h3>{gameProgress.length?<div className="aa-room-list">{gameProgress.slice(0,5).map(g=>{const def=gameDefinition(g.game_id);return <article key={g.game_id}><span>🎮</span><div><b>{def?.title||g.game_id}</b><small>{g.plays} لعب • أفضل نتيجة {g.best_score}</small></div><strong>{g.best_stars||0}/3</strong></article>})}</div>:<p style={{color:"var(--aa-muted)"}}>ابدأ أول لعبة وستظهر أفضل نتائجك هنا.</p>}<div style={{marginTop:14}}><Button kind="secondary" icon="game" onClick={()=>go("/games")}>عالم الألعاب</Button></div></article></div></Section>
    <Section eyebrow="دلوقتي" title="اختار الخطوة اللي بعدها"><div className="aa-world-grid"><Card className="aa-world-card" icon="quran" title="أكمل الحفظ" text="جلسة قصيرة جديدة" tone="sky" action="ابدأ" onClick={()=>go("/memorize")}/><Card className="aa-world-card" icon="review" title="راجع محفوظك" text="ثبّت اللي اتعلمته" tone="mint" action="راجع" onClick={()=>go("/review")}/><Card className="aa-world-card" icon="game" title="العب شوية" text="تعلم وجمع نجوم" tone="lavender" action="يلا" onClick={()=>go("/games")}/></div></Section>
  </AppShell>;
}
