import React, { useEffect, useMemo, useState } from "react";
import Icon from "./Icon.jsx";
import { getActiveChildId, getCurrentUser, getProgress, listAchievements, listChildren } from "./api.js";
import { GameEngine } from "./gameEngine.js";
import { gameDefinition } from "./gameDefinitions.js";
import { getSurah } from "./quranData.js";

function routePath(){return typeof window.__ABU_ROUTE_PATH__==="function"?window.__ABU_ROUTE_PATH__():window.location.pathname;}
function navigate(path){if(routePath()!==path){history.pushState({},"",path);window.dispatchEvent(new PopStateEvent("popstate"));}}

export default function RoomPage(){
  const [user,setUser]=useState(undefined);const [child,setChild]=useState(null);const [progress,setProgress]=useState([]);const [achievements,setAchievements]=useState([]);const [gameProgress,setGameProgress]=useState([]);const [reviewQueue,setReviewQueue]=useState([]);const [err,setErr]=useState("");
  useEffect(()=>{let alive=true;(async()=>{try{const current=await getCurrentUser();if(!alive)return;if(!current)return navigate("/login");if(current.accountType==="teacher")return;setUser(current);const kids=await listChildren(current);const selected=kids.find(k=>k.id===getActiveChildId())||kids[0]||null;if(!alive)return;setChild(selected);if(selected){const [rows,badges,games,due]=await Promise.all([getProgress(selected.id),listAchievements(selected.id),GameEngine.progress(selected.id),GameEngine.dueReview(selected.id,12)]);if(alive){setProgress(rows||[]);setAchievements(badges||[]);setGameProgress(games||[]);setReviewQueue(due||[]);}}}catch(e){if(alive)setErr(e.message||"تعذر تحميل غرفة الطفل.");}})();return()=>{alive=false;};},[]);
  if(user===undefined)return <div className="center"><i className="spinner"/><p>جارٍ تجهيز الغرفة...</p></div>;
  const avg=useMemo(()=>progress.length?Math.round(progress.reduce((sum,row)=>sum+Number(row.memorized_percent||0),0)/progress.length):0,[progress]);
  const mastered=progress.filter(r=>r.status==="mastered").length;const gamesMastered=gameProgress.filter(g=>Number(g.best_stars||0)>=3).length;
  const weakBySurah=useMemo(()=>{const map=new Map();for(const item of reviewQueue){if(!map.has(item.surah_number))map.set(item.surah_number,[]);map.get(item.surah_number).push(item);}return [...map.entries()].slice(0,4);},[reviewQueue]);
  return <div className="app room-v2" dir="rtl"><header className="room-topbar"><div className="wrap nav"><button className="brand" onClick={()=>navigate("/child")}><span className="logo"><Icon name="room" size={22}/></span><span><b>غرفتي</b><small>ملخص رحلتي</small></span></button><div className="actions"><button className="secondary" onClick={()=>navigate("/child")}><Icon name="child" size={17}/> وضع الطفل</button><button className="secondary" onClick={()=>navigate("/achievements")}><Icon name="trophy" size={17}/> الإنجازات</button></div></div></header><main className="wrap page room-page">
    <section className="room-hero"><div className="room-avatar"><Icon name="child" size={54}/></div><div className="grow"><span>مساحتي الخاصة</span><h1>غرفة {child?.display_name||"بطلنا"}</h1><p>{reviewQueue.length?`اليوم عندك ${reviewQueue.length} آية في المراجعة الذكية. نقدر نثبتهم باللعب والمراجعة.`:"كل تقدمك ونقاطك ونجومك تظهر هنا في مكان واحد."}</p></div><div className="room-level"><Icon name="flame" size={24}/><b>{child?.streak||0}</b><span>يوم متواصل</span></div></section>{err&&<div className="msg error">{err}</div>}
    <section className="room-stats"><article><span className="room-stat-icon gold"><Icon name="trophy" size={25}/></span><b>{child?.points||0}</b><small>نقطة</small></article><article><span className="room-stat-icon sun"><Icon name="star" size={25}/></span><b>{child?.stars||0}</b><small>نجمة</small></article><article><span className="room-stat-icon mint"><Icon name="game" size={25}/></span><b>{gamesMastered}</b><small>ألعاب متقنة</small></article><article><span className="room-stat-icon sky"><Icon name="review" size={25}/></span><b>{reviewQueue.length}</b><small>آيات تحتاج مراجعة</small></article></section>
    <div className="room-grid"><section className="panel room-progress-panel"><div className="room-section-head"><div><span>التقدم</span><h2>رحلة الحفظ</h2></div><button className="secondary" onClick={()=>navigate("/quran")}><Icon name="quran" size={17}/> القرآن</button></div><div className="room-progress-visual"><div className="room-big-progress"><strong>{avg}%</strong><span>متوسط الحفظ</span></div><div className="grow"><div className="bar big"><i style={{width:`${avg}%`}}/></div><p>{progress.length?`بدأت ${progress.length} سورة، وأتقنت ${mastered} منها حتى الآن.`:"ابدأ أول جلسة حفظ وستظهر رحلتك هنا."}</p></div></div></section><section className="panel room-achievement-panel"><div className="room-section-head"><div><span>{achievements.length} ميدالية</span><h2>إنجازاتي</h2></div></div><div className="room-badge-row">{achievements.slice(-4).map((item,i)=><span key={item.id||item.slug||i}><Icon name={i%2?"medal":"trophy"} size={27}/></span>)}{!achievements.length&&<div className="room-empty-mini"><Icon name="lock" size={25}/><small>ابدأ الأنشطة لفتح أول ميدالية.</small></div>}</div><button className="primary full" onClick={()=>navigate("/achievements")}><Icon name="trophy" size={18}/> عرض كل الإنجازات</button></section></div>
    <div className="room-grid room-learning-intel"><section className="panel"><div className="room-section-head"><div><span>المراجعة الذكية</span><h2>نقاط تحتاج تثبيت</h2></div><button className="secondary" onClick={()=>navigate("/review")}><Icon name="review" size={17}/> ابدأ المراجعة</button></div>{weakBySurah.length?<div className="room-review-list">{weakBySurah.map(([surah,items])=><article key={surah}><span><Icon name="quran" size={21}/></span><div className="grow"><b>سورة {getSurah(surah)?.name||surah}</b><small>الآيات: {items.map(x=>x.ayah_number).join("، ")}</small></div><strong>{Math.max(...items.map(x=>x.priority))}</strong></article>)}</div>:<div className="room-empty-mini large"><Icon name="check" size={29}/><small>لا توجد آيات مستحقة للمراجعة الذكية الآن.</small></div>}</section>
    <section className="panel"><div className="room-section-head"><div><span>الألعاب</span><h2>إتقاني في الألعاب</h2></div><button className="secondary" onClick={()=>navigate("/games")}><Icon name="game" size={17}/> عالم الألعاب</button></div>{gameProgress.length?<div className="room-game-progress">{gameProgress.slice(0,5).map(g=>{const def=gameDefinition(g.game_id);return <article key={g.game_id}><span><Icon name={def?.icon||"game"} size={22}/></span><div className="grow"><b>{def?.title||g.game_id}</b><small>{g.plays} لعب • أفضل نتيجة {g.best_score}</small></div><div className="mini-stars">{[1,2,3].map(n=><Icon key={n} name="star" size={15} className={n<=Number(g.best_stars||0)?"earned":""}/>)}</div></article>})}</div>:<p className="muted">ابدأ أول لعبة من عالم الألعاب وستظهر أفضل نتائجك هنا.</p>}</section></div>
    <section className="room-actions"><button onClick={()=>navigate("/memorize")}><span><Icon name="quran" size={29}/></span><b>أكمل الحفظ</b><small>جلسة قصيرة جديدة</small></button><button onClick={()=>navigate("/review")}><span><Icon name="review" size={29}/></span><b>راجع محفوظك</b><small>ثبّت ما تعلمته</small></button><button onClick={()=>navigate("/games")}><span><Icon name="game" size={29}/></span><b>اذهب للألعاب</b><small>تعلم والعب</small></button></section>
  </main><footer><div className="wrap">أبو العزايم للحفظ الممتع • كل إنجاز وخطأ في اللعبة يساعدنا نبني مراجعة أذكى.</div></footer></div>;
}
