import React,{useEffect,useMemo,useState} from "react";
import {claimReward,createTeacherClass,dayKey,getCurrentUser,getProgress,recordReview,rest,signOut,teacherOverview} from "./api.js";
import {getSurah} from "./surahCatalog.js";
import Icon from "./Icon.jsx";
import {AppShell,Button,Card,Empty,Hero,Metric,ProgressBar,Section,TEACHER_NAV,go,routePath} from "./ui-v4.jsx";

function formatDate(value){if(!value)return "لا يوجد نشاط بعد";try{return new Intl.DateTimeFormat("ar-EG",{dateStyle:"medium",timeStyle:"short"}).format(new Date(value));}catch{return value;}}
function Loading(){return <div className="center"><i className="spinner"/><p>جارٍ تجهيز بوابة المعلم...</p></div>;}
function ErrorBox({text}){return text?<div className="msg error">{text}</div>:null;}

function StudentRow({student}){return <button className="aa-table-row" style={{width:"100%",textAlign:"right",cursor:"pointer"}} onClick={()=>go(`/teacher/student/${student.id}`)}><span><Icon name="child" size={22}/></span><div><b>{student.display_name}</b><small>{student.classes.join(" • ")||"بدون فصل"} • آخر نشاط: {formatDate(student.lastActivityAt)}</small></div><strong>{student.memorizedAverage}%</strong></button>;}

function Dashboard({data}){
  const recent=[...data.students].sort((a,b)=>new Date(b.lastActivityAt||0)-new Date(a.lastActivityAt||0)).slice(0,5);const mastered=data.students.reduce((s,x)=>s+Number(x.masteredCount||0),0);
  return <>
    <Hero eyebrow="لوحة المعلم" title="متابعة واضحة من غير زحمة" description="الفصول والطلاب والتقدم والتسميع في مكان واحد، بدون خلط واجهة المعلم بواجهة الطفل." icon="teacher" tone="sky"/>
    <div className="aa-teacher-layout"><Metric icon="books" label="الفصول" value={data.classes.length} tone="sky"/><Metric icon="users" label="الطلاب" value={data.students.length} tone="mint"/><Metric icon="review" label="مراجعات اليوم" value={data.sessionsToday} tone="lavender"/><Metric icon="circleCheck" label="سور متقنة" value={mastered} tone="gold"/></div>
    <Section eyebrow="آخر النشاط" title="الطلاب الأحدث نشاطًا" action={<Button kind="secondary" icon="users" onClick={()=>go("/teacher/students")}>كل الطلاب</Button>}>{recent.length?<div className="aa-table-list">{recent.map(s=><StudentRow key={s.id} student={s}/>)}</div>:<Empty icon="users" title="لا يوجد طلاب مرتبطون بعد" text="أنشئ فصلًا وشارك كود الربط مع ولي الأمر." action={<Button onClick={()=>go("/teacher/classes")}>إدارة الفصول</Button>}/>}</Section>
  </>;
}

function Classes({user,data,reload}){
  const [name,setName]=useState(""),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[error,setError]=useState("");
  async function create(e){e.preventDefault();if(!name.trim())return;setBusy(true);setError("");setMessage("");try{await createTeacherClass(user.id,name.trim());setName("");setMessage("تم إنشاء الفصل بنجاح.");await reload();}catch(e){setError(e.message||"تعذر إنشاء الفصل.");}finally{setBusy(false);}}
  async function copy(code){try{await navigator.clipboard.writeText(code);setMessage(`تم نسخ الكود ${code}`);}catch{setMessage(`كود الفصل: ${code}`);}}
  return <><Hero eyebrow="إدارة الفصول" title="فصولي" description="فصل لكل مجموعة، وكود ربط واحد واضح لولي الأمر." icon="books" tone="mint"/>{message&&<div className="msg ok">{message}</div>}<ErrorBox text={error}/><div className="aa-dashboard-grid"><aside className="aa-form-card"><h3 style={{marginTop:0}}>فصل جديد</h3><form className="aa-form" onSubmit={create}><label>اسم الفصل<input value={name} onChange={e=>setName(e.target.value)} placeholder="مثال: حلقة جزء عمّ" maxLength="80" required/></label><Button type="submit" className="full" disabled={busy}>{busy?"جارٍ الإنشاء...":"إنشاء الفصل"}</Button></form></aside><section>{data.classes.length?<div className="aa-person-list">{data.classes.map(c=>{const count=data.students.filter(s=>s.classes.includes(c.name)).length;return <article className="aa-person-card" key={c.id}><div className="aa-person-head"><span className="aa-avatar"><Icon name="books" size={27}/></span><div><b>{c.name}</b><small>{count} طالب مرتبط</small></div></div><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:10,flexWrap:"wrap"}}><span><small style={{color:"var(--aa-muted)"}}>كود الربط</small><b style={{display:"block",fontSize:20}}>{c.join_code}</b></span><Button kind="secondary" icon="copy" onClick={()=>copy(c.join_code)}>نسخ الكود</Button></div></article>;})}</div>:<Empty icon="books" title="أنشئ أول فصل" text="بعد الإنشاء يظهر كود ربط يضيف به ولي الأمر طفله."/>}</section></div></>;
}

function Students({data}){
  const [search,setSearch]=useState(""),[className,setClassName]=useState("all");const filtered=useMemo(()=>data.students.filter(s=>{const q=search.trim().toLowerCase();return(!q||s.display_name.toLowerCase().includes(q)||s.classes.join(" ").toLowerCase().includes(q))&&(className==="all"||s.classes.includes(className));}),[data.students,search,className]);
  return <><Hero eyebrow="الطلاب" title="متابعة الطلاب" description="ابحث باسم الطالب أو الفصل، وبعدها افتح ملف الطالب مباشرة." icon="users" tone="sky"/><Section><div className="aa-quran-toolbar"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="ابحث باسم الطالب أو الفصل"/><select value={className} onChange={e=>setClassName(e.target.value)}><option value="all">كل الفصول</option>{data.classes.map(c=><option key={c.id} value={c.name}>{c.name}</option>)}</select></div>{filtered.length?<div className="aa-table-list">{filtered.map(s=><StudentRow key={s.id} student={s}/>)}</div>:<Empty icon="search" title="لا توجد نتائج" text={data.students.length?"غيّر البحث أو الفلتر.":"لا يوجد طلاب مرتبطون حتى الآن."}/>}</Section></>;
}

function StudentDetail({user,data,studentId,reloadOverview}){
  const summary=data.students.find(s=>s.id===studentId);const [progress,setProgress]=useState([]),[reviews,setReviews]=useState([]),[score,setScore]=useState(100),[surahNumber,setSurahNumber]=useState(""),[notes,setNotes]=useState(""),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[error,setError]=useState("");
  async function load(){if(!summary)return;try{const [rows,reviewRows]=await Promise.all([getProgress(studentId),rest(`/review_events?child_id=eq.${encodeURIComponent(studentId)}&select=id,surah_number,score,notes,reviewed_at,created_by&order=reviewed_at.desc&limit=20`)]);setProgress(rows||[]);setReviews(reviewRows||[]);const first=(rows||[]).find(r=>Number(r.memorized_percent||0)>0);setSurahNumber(v=>v||(first?String(first.surah_number):""));}catch(e){setError(e.message||"تعذر تحميل ملف الطالب.");}}
  useEffect(()=>{load();},[studentId,summary?.id]);
  if(!summary)return <Empty icon="lock" title="الطالب غير متاح" text="قد يكون غير مرتبط بفصولك الآن." action={<Button onClick={()=>go("/teacher/students")}>كل الطلاب</Button>}/>;
  const active=progress.filter(r=>Number(r.memorized_percent||0)>0);
  async function submitReview(e){e.preventDefault();if(!surahNumber)return;setBusy(true);setMessage("");setError("");try{const n=Number(surahNumber);await recordReview(user,studentId,n,Number(score),notes.trim());const reward=await claimReward(studentId,"review_session",dayKey("review",n)).catch(()=>null);const r=Array.isArray(reward)?reward[0]:reward;setMessage(r?.awarded===false?"تم تسجيل المراجعة. مكافأة اليوم حصل عليها الطالب مسبقًا.":"تم تسجيل المراجعة وتحديث التقدم.");setNotes("");await Promise.all([load(),reloadOverview()]);}catch(e){setError(e.message||"تعذر تسجيل المراجعة.");}finally{setBusy(false);}}
  return <><Button kind="ghost" icon="arrow" onClick={()=>go("/teacher/students")}>العودة للطلاب</Button><Hero eyebrow={summary.classes.join(" • ")||"بدون فصل"} title={summary.display_name} description={`آخر نشاط: ${formatDate(summary.lastActivityAt)}`} icon="child" tone="lavender"/><div className="aa-teacher-layout"><Metric icon="quran" label="متوسط الحفظ" value={`${summary.memorizedAverage}%`} tone="sky"/><Metric icon="review" label="متوسط المراجعة" value={`${summary.reviewAverage}%`} tone="mint"/><Metric icon="circleCheck" label="سور متقنة" value={summary.masteredCount} tone="gold"/><Metric icon="books" label="سور بدأت" value={active.length} tone="lavender"/></div><div className="aa-dashboard-grid" style={{marginTop:24}}><section><Section eyebrow="التقدم" title="السور التي بدأها">{active.length?<div className="aa-person-list">{active.map(row=>{const s=getSurah(row.surah_number);return <article className="aa-person-card" key={row.surah_number}><div style={{display:"flex",justifyContent:"space-between",gap:10}}><b>سورة {s?.name||row.surah_name||row.surah_number}</b><small>{Number(row.memorized_percent||0)}% حفظ</small></div><ProgressBar value={Number(row.memorized_percent||0)} label={`مراجعة ${Number(row.review_percent||0)}%`}/></article>;})}</div>:<Empty icon="quran" title="لم يبدأ الحفظ بعد" text="سيظهر التقدم بعد أول جلسة."/>}</Section></section><aside className="aa-form-card"><h3 style={{marginTop:0}}>تسجيل مراجعة</h3>{active.length?<form className="aa-form" onSubmit={submitReview}><label>السورة<select value={surahNumber} onChange={e=>setSurahNumber(e.target.value)} required>{active.map(row=>{const s=getSurah(row.surah_number);return <option key={row.surah_number} value={row.surah_number}>سورة {s?.name||row.surah_name||row.surah_number}</option>})}</select></label><label>التقييم<select value={score} onChange={e=>setScore(Number(e.target.value))}><option value="100">ممتاز — 100%</option><option value="90">ممتاز جدًا — 90%</option><option value="80">جيد — 80%</option><option value="60">يحتاج تدريب — 60%</option></select></label><label>ملاحظات<input value={notes} onChange={e=>setNotes(e.target.value)} maxLength="300" placeholder="ملاحظة اختيارية"/></label><Button type="submit" className="full" disabled={busy}>{busy?"جارٍ التسجيل...":"حفظ نتيجة المراجعة"}</Button></form>:<p style={{color:"var(--aa-muted)",fontSize:12}}>لا يمكن تسجيل مراجعة قبل بدء حفظ سورة.</p>}{message&&<div className="msg ok">{message}</div>}<ErrorBox text={error}/></aside></div><Section eyebrow="السجل" title="آخر المراجعات">{reviews.length?<div className="aa-table-list">{reviews.map(r=>{const s=getSurah(r.surah_number);return <article className="aa-table-row" key={r.id}><span><Icon name="review" size={21}/></span><div><b>سورة {s?.name||r.surah_number}</b><small>{formatDate(r.reviewed_at)}{r.notes?` • ${r.notes}`:""}</small></div><strong>{r.score}%</strong></article>})}</div>:<Empty icon="review" title="لا توجد مراجعات بعد"/>}</Section></>;
}

export default function TeacherPortal(){
  const [user,setUser]=useState(undefined),[data,setData]=useState({classes:[],students:[],sessionsToday:0}),[loading,setLoading]=useState(true),[error,setError]=useState(""),[path,setPath]=useState(routePath());
  async function reload(){if(!user?.id)return;setLoading(true);try{setData(await teacherOverview(user.id));setError("");}catch(e){setError(e.message||"تعذر تحميل بيانات المعلم.");}finally{setLoading(false);}}
  useEffect(()=>{const sync=()=>setPath(routePath());window.addEventListener("popstate",sync);return()=>window.removeEventListener("popstate",sync);},[]);
  useEffect(()=>{let alive=true;(async()=>{try{const current=await getCurrentUser();if(!alive)return;if(!current)return go("/login");if(!["teacher","admin"].includes(current.accountType))return go("/family");setUser(current);}catch(e){if(alive)setError(e.message||"تعذر التحقق من حساب المعلم.");}})();return()=>{alive=false;};},[]);
  useEffect(()=>{if(user?.id)reload();},[user?.id]);
  if(user===undefined)return <Loading/>;
  async function logout(){await signOut();go("/");}
  let page;if(loading&&!data.classes.length&&!data.students.length)page=<Loading/>;else{const match=path.match(/^\/teacher\/student\/([0-9a-f-]+)$/i);if(path==="/teacher"||path==="/teacher/")page=<Dashboard data={data}/>;else if(path==="/teacher/classes")page=<Classes user={user} data={data} reload={reload}/>;else if(path==="/teacher/students")page=<Students data={data}/>;else if(match)page=<StudentDetail user={user} data={data} studentId={match[1]} reloadOverview={reload}/>;else page=<Empty icon="target" title="الصفحة غير موجودة" action={<Button onClick={()=>go("/teacher")}>لوحة المعلم</Button>}/>;}
  return <AppShell mode="teacher" subtitle="بوابة المعلم" nav={TEACHER_NAV} actions={<><span style={{fontSize:12,fontWeight:900}}>{user?.name||"المعلم"}</span><Button kind="ghost" icon="logout" onClick={logout}>خروج</Button></>} footer="أبو العزايم • بوابة المعلم للمتابعة والتسميع.">{error&&<ErrorBox text={error}/>} {page}</AppShell>;
}
