import React, { useEffect, useMemo, useState } from "react";
import Icon from "./Icon.jsx";
import { getCurrentUser, rest, teacherOverview } from "./api.js";
import { gameDefinition } from "./gameDefinitions.js";
import { getSurah } from "./quranData.js";

function routePath(){return typeof window.__ABU_ROUTE_PATH__==="function"?window.__ABU_ROUTE_PATH__():window.location.pathname;}
function navigate(path){if(routePath()!==path){history.pushState({},"",path);window.dispatchEvent(new PopStateEvent("popstate"));}}
function gameTitle(id){return gameDefinition(id)?.title||id.replaceAll("_"," ");}
function formatDate(value){if(!value)return "—";try{return new Intl.DateTimeFormat("ar-EG",{dateStyle:"medium"}).format(new Date(value));}catch{return value;}}

export default function TeacherGameReports(){
  const [user,setUser]=useState(undefined);const [students,setStudents]=useState([]);const [selected,setSelected]=useState("");const [games,setGames]=useState([]);const [review,setReview]=useState([]);const [events,setEvents]=useState([]);const [loading,setLoading]=useState(false);const [error,setError]=useState("");
  useEffect(()=>{let alive=true;(async()=>{try{const current=await getCurrentUser();if(!alive)return;if(!current)return navigate("/login");setUser(current);const overview=await teacherOverview(current.id);if(!alive)return;setStudents(overview.students||[]);setSelected(x=>x||(overview.students?.[0]?.id||""));}catch(e){if(alive)setError(e.message||"تعذر تحميل طلاب المعلم.");}})();return()=>{alive=false;};},[]);
  useEffect(()=>{if(!selected)return;let alive=true;setLoading(true);setError("");(async()=>{try{const [gp,rq,ev]=await Promise.all([
    rest(`/game_progress?child_id=eq.${encodeURIComponent(selected)}&select=*&order=plays.desc`),
    rest(`/review_queue?child_id=eq.${encodeURIComponent(selected)}&select=*&order=priority.desc,last_error_at.desc&limit=30`),
    rest(`/game_ayah_events?child_id=eq.${encodeURIComponent(selected)}&is_correct=eq.false&select=game_id,surah_number,ayah_number,question_type,created_at&order=created_at.desc&limit=30`),
  ]);if(alive){setGames(gp||[]);setReview(rq||[]);setEvents(ev||[]);}}catch(e){if(alive)setError(e.message||"تعذر تحميل تقارير الألعاب.");}finally{if(alive)setLoading(false);}})();return()=>{alive=false;};},[selected]);
  const student=students.find(s=>s.id===selected)||null;
  const summary=useMemo(()=>{const played=[...games].filter(g=>Number(g.plays||0)>0);const favorite=[...played].sort((a,b)=>Number(b.plays)-Number(a.plays))[0]||null;const weakest=[...played].sort((a,b)=>Number(a.mastery_score||0)-Number(b.mastery_score||0))[0]||null;return {plays:played.reduce((s,g)=>s+Number(g.plays||0),0),completions:played.reduce((s,g)=>s+Number(g.completions||0),0),mastered:played.filter(g=>Number(g.best_stars||0)>=3).length,favorite,weakest};},[games]);
  const groupedReview=useMemo(()=>{const map=new Map();for(const item of review){if(!map.has(item.surah_number))map.set(item.surah_number,[]);map.get(item.surah_number).push(item);}return [...map.entries()].sort((a,b)=>Math.max(...b[1].map(x=>x.priority))-Math.max(...a[1].map(x=>x.priority)));},[review]);
  if(user===undefined)return <div className="center"><i className="spinner"/><p>جارٍ تجهيز تقارير الألعاب...</p></div>;
  return <div className="app teacher-game-reports" dir="rtl"><main className="wrap page teacherPage">
    <section className="teacher-game-report-hero"><div><span><Icon name="game" size={18}/> تقارير الألعاب</span><h1>أثر اللعب على الحفظ والمراجعة</h1><p>النتائج هنا مبنية على جلسات اللعب الفعلية وأخطاء الآيات المسجلة في GameEngine.</p></div><div className="teacher-game-report-art"><Icon name="chart" size={58}/></div></section>
    <section className="teacher-report-picker"><label>اختر الطالب<select value={selected} onChange={e=>setSelected(e.target.value)}><option value="">اختر طالبًا</option>{students.map(s=><option key={s.id} value={s.id}>{s.display_name} — {s.classes.join("، ")}</option>)}</select></label><button className="secondary" onClick={()=>navigate("/teacher/students")}><Icon name="users" size={17}/> الطلاب</button></section>
    {error&&<div className="msg error">{error}</div>}{loading&&<div className="center"><i className="spinner"/><p>تحميل بيانات الألعاب...</p></div>}
    {!loading&&student&&<>
      <section className="teacher-game-summary"><article><span><Icon name="game" size={24}/></span><b>{summary.plays}</b><small>مرة لعب</small></article><article><span><Icon name="check" size={24}/></span><b>{summary.completions}</b><small>لعبة مكتملة</small></article><article><span><Icon name="star" size={24}/></span><b>{summary.mastered}</b><small>ألعاب بإتقان 3 نجوم</small></article><article><span><Icon name="review" size={24}/></span><b>{review.length}</b><small>آيات في المراجعة الذكية</small></article></section>
      <div className="teacher-game-insight-grid"><section className="panel"><div className="teacherSectionHead"><div><span>السلوك</span><h2>ملخص {student.display_name}</h2></div></div><div className="teacher-game-highlight"><span><Icon name="trophy" size={27}/></span><div><small>أكثر لعبة يستخدمها</small><b>{summary.favorite?gameTitle(summary.favorite.game_id):"لا توجد بيانات بعد"}</b>{summary.favorite&&<p>{summary.favorite.plays} مرة • أفضل نتيجة {summary.favorite.best_score}</p>}</div></div><div className="teacher-game-highlight warning"><span><Icon name="target" size={27}/></span><div><small>أكثر لعبة تحتاج دعمًا</small><b>{summary.weakest?gameTitle(summary.weakest.game_id):"لا توجد بيانات بعد"}</b>{summary.weakest&&<p>مؤشر الإتقان {Number(summary.weakest.mastery_score||0).toFixed(0)}%</p>}</div></div></section>
      <section className="panel"><div className="teacherSectionHead"><div><span>آخر الأخطاء</span><h2>أخطاء مسجلة من الألعاب</h2></div></div>{events.length?<div className="teacher-error-feed">{events.slice(0,8).map((e,i)=><article key={`${e.created_at}-${i}`}><span className="history-icon"><Icon name="review" size={19}/></span><div className="grow"><b>سورة {getSurah(e.surah_number)?.name||e.surah_number} — آية {e.ayah_number}</b><small>{gameTitle(e.game_id)} • {e.question_type} • {formatDate(e.created_at)}</small></div></article>)}</div>:<p className="muted">لا توجد أخطاء مسجلة بعد.</p>}</section></div>
      <section className="panel teacher-games-table"><div className="teacherSectionHead"><div><span>{games.length} لعبة</span><h2>أداء الألعاب</h2></div></div>{games.length?<div className="game-report-grid">{games.map(g=>{const def=gameDefinition(g.game_id);return <article key={g.game_id}><div className="game-report-icon"><Icon name={def?.icon||"game"} size={25}/></div><div className="grow"><h3>{gameTitle(g.game_id)}</h3><div className="game-report-metrics"><span>{g.plays} لعب</span><span>{g.completions} إكمال</span><span>{g.best_score} أفضل Score</span><span>{g.best_stars}/3 نجوم</span><span>{Number(g.mastery_score||0).toFixed(0)}% إتقان</span></div></div>{def?.route&&<button className="secondary" onClick={()=>navigate(def.route)}>معاينة اللعبة</button>}</article>})}</div>:<p className="muted">لم يبدأ الطالب ألعاب GameEngine الجديدة بعد.</p>}</section>
      <section className="panel teacher-review-queue"><div className="teacherSectionHead"><div><span>Review Queue</span><h2>الآيات التي تحتاج مراجعة</h2></div></div>{groupedReview.length?<div className="review-queue-groups">{groupedReview.map(([surah,items])=><article key={surah}><div className="review-surah-head"><span><Icon name="quran" size={22}/></span><div><b>سورة {getSurah(surah)?.name||surah}</b><small>{items.length} آية مسجلة</small></div></div><div className="review-ayah-chips">{items.map(item=><span key={item.ayah_number} className={item.priority>=7?"high":item.priority>=4?"medium":""}>آية {item.ayah_number}<small>أخطاء {item.error_count} • أولوية {item.priority}</small></span>)}</div></article>)}</div>:<div className="teacherEmpty teacherEmptyV2"><span className="teacher-empty-icon"><Icon name="check" size={36}/></span><h3>لا توجد آيات معلقة</h3><p>عندما يخطئ الطفل في آية داخل لعبة جديدة ستظهر هنا تلقائيًا.</p></div>}</section>
    </>}
    {!loading&&!student&&<div className="teacherEmpty teacherEmptyV2"><span className="teacher-empty-icon"><Icon name="users" size={36}/></span><h3>اختر طالبًا</h3><p>اختر طالبًا مرتبطًا بأحد فصولك لعرض أثر الألعاب.</p></div>}
  </main></div>;
}
