import React,{useMemo,useState} from "react";
import {SURAHS,getSurah} from "./surahCatalog.js";
import {selectSurah} from "./QuranPage.jsx";
import {Button,Empty,Hero,Section,go,getLessonContext,saveLessonContext} from "./ui-v4.jsx";

export default function TeacherQuranPreview(){
  const [query,setQuery]=useState(""); const [lessonContext,setLessonContext]=useState(()=>getLessonContext());
  const currentSurah=lessonContext?.surahNumber?getSurah(lessonContext.surahNumber):null;
  const maxAyahs=currentSurah?.ayahs||1;
  const visible=useMemo(()=>{const q=query.trim().replace(/^سورة\s+/i,"");return SURAHS.filter(s=>!q||s.name.includes(q)||String(s.number)===q);},[query]);
  function open(surah){const next={...(lessonContext||{}),surah:surah.name,surahNumber:surah.number,number:1,phase:"اختيار السورة"};saveLessonContext(next);setLessonContext(next);selectSurah(surah.number);go("/memorize");}
  return <div className="aa-preview-page" dir="rtl"><Hero eyebrow="١١٤ سورة • معاينة آمنة" title="القرآن الكريم" description="تصفح السور وافتح أي سورة في محاكاة جلسة الحفظ، بدون تعديل تقدم طالب." icon="quran" tone="sky"/><div className="msg ok">التصفح والمعاينة لا يغيران تقدم أي طالب.</div>{lessonContext&&<div className="aa-lesson-context-editor"><label>مرحلة الحصة<select value={lessonContext.phase||"اختيار السورة"} onChange={e=>{const next={...lessonContext,phase:e.target.value};saveLessonContext(next);setLessonContext(next);}}><option>اختيار السورة</option><option>شرح</option><option>تسميع</option><option>مراجعة</option><option>لعبة تطبيقية</option></select></label><label>الآية الحالية<input type="number" min="1" max={maxAyahs} value={Math.min(maxAyahs,Math.max(1,Number(lessonContext.number)||1))} onChange={e=>{const number=Math.min(maxAyahs,Math.max(1,Number(e.target.value)||1));const next={...lessonContext,number};saveLessonContext(next);setLessonContext(next);}}/><small style={{fontSize:10,color:"var(--aa-muted)"}}>من ١ إلى {maxAyahs}</small></label></div>}{lessonContext&&<div className="aa-lesson-context-bar"><strong>سياق الحصة</strong><span>سورة {lessonContext.surah||"غير محددة"}{lessonContext.number?" — الآية "+lessonContext.number:""}</span><Button kind="secondary" onClick={()=>go("/teacher/whiteboard")}>العودة للسبورة</Button></div>}<Section eyebrow="ابحث" title="السور"><div className="aa-quran-toolbar"><input type="search" placeholder="ابحث باسم السورة أو رقمها" value={query} onChange={e=>setQuery(e.target.value)}/><span style={{alignSelf:"center",fontSize:11,color:"var(--aa-muted)"}}>{visible.length} من ١١٤ سورة</span></div><div className="aa-surah-grid">{visible.map(s=><article className="aa-card aa-surah-card" key={s.number}><span className="aa-surah-num">{s.number}</span><h3>سورة {s.name}</h3><small>{s.ayahs} آية</small><Button onClick={()=>open(s)}>معاينة الحفظ</Button></article>)}</div>{!visible.length&&<Empty icon="search" title="لا توجد سورة مطابقة"/>}</Section></div>;
}
