import React, { useEffect, useMemo, useState } from "react";
import Icon from "./Icon.jsx";
import { getCurrentUser, rest, teacherOverview } from "./api.js";
import { gameDefinition } from "./gameRegistry.js";
import { getSurah } from "./surahCatalog.js";

function routePath(){return typeof window.__ABU_ROUTE_PATH__==="function"?window.__ABU_ROUTE_PATH__():window.location.pathname;}
function navigate(path){if(routePath()!==path){history.pushState({},"",path);window.dispatchEvent(new PopStateEvent("popstate"));}}
function gameTitle(id){return gameDefinition(id)?.title||String(id||"").replaceAll("_"," ");}
function formatDate(value){if(!value)return "—";try{return new Intl.DateTimeFormat("ar-EG",{dateStyle:"medium"}).format(new Date(value));}catch{return value;}}
function pct(value,total){return total?Math.round((Number(value||0)/Number(total))*100):0;}
function questionLabel(type){return ({next_ayah:"الآية التالية",missing_word:"الكلمة الناقصة",ayah_order:"ترتيب الآيات",word_order:"ترتيب الكلمات",chunk_order:"ترتيب أجزاء الآية",surah_name:"اسم السورة",surah_order:"ترتيب السور",ayah_number:"رقم الآية",ayah_beginning:"بداية الآية",beginning_ending:"البداية والنهاية",matching:"المطابقة"})[type]||type||"سؤال";}

export default function TeacherGameReports(){
  const [user,setUser]=useState(undefined);const [students,setStudents]=useState([]);const [selected,setSelected]=useState("");const [games,setGames]=useState([]);const [review,setReview]=useState([]);const [events,setEvents]=useState([]);const [loading,setLoading]=useState(false);const [error,setError]=useState("");
  useEffect(()=>{let alive=true;(async()=>{try{const current=await getCurrentUser();if(!alive)return;if(!current)return navigate("/login");setUser(current);const overview=await teacherOverview(current.id);if(!alive)return;setStudents(overview.students||[]);setSelected(x=>x||(overview.students?.[0]?.id||""));}catch(e){if(alive)setError(e.message||"تعذر تحميل طلاب المعلم.");}})();return()=>{alive=false;};},[]);
  useEffect(()=>{if(!selected)return;let alive=true;setLoading(true);setError("");(async()=>{try{const [gp,rq,ev]=await Promise.all([
    rest(`/game_progress?child_id=eq.${encodeURIComponent(selected)}&select=*&order=plays.desc`),
    rest(`/review_queue?child_id=eq.${encodeURIComponent(selected)}&select=*&order=priority.desc,last_error_at.desc&limit=100`),
    rest(`/game_ayah_events?child_id=eq.${encodeURIComponent(selected)}&select=game_id,surah_number,ayah_number,question_type,is_correct,response_time_ms,created_at&order=created_at.desc&limit=300`),
  ]);if(alive){setGames(gp||[]);setReview(rq||[]);setEvents(ev||[]);}}catch(e){if(alive)setError(e.message||"تعذر تحميل تقارير الألعاب.");}finally{if(alive)setLoading(false);}})();return()=>{alive=false;};},[selected]);
  const student=students.find(s=>s.id===selected)||null;
  const summary=useMemo(()=>{const played=[...games].filter(g=>Number(g.plays||0)>0);const favorite=[...played].sort((a,b)=>Number(b.plays)-Number(a.plays))[0]||null;const weakest=[...played].sort((a,b)=>Number(a.mastery_score||0)-Number(b.mastery_score||0))[0]||null;const correct=played.reduce((s,g)=>s+Number(g.total_correct||0),0),wrong=played.reduce((s,g)=>s+Number(g.total_wrong||0),0),attempts=correct+wrong;const timed=events.filter(e=>e.response_time_ms!=null);const averageMs=timed.length?Math.round(timed.reduce((s,e)=>s+Number(e.response_time_ms||0),0)/timed.length):0;const now=Date.now();return {plays:played.reduce((s,g)=>s+Number(g.plays||0),0),completions:played.reduce((s,g)=>s+Number(g.completions||0),0),mastered:played.filter(g=>Number(g.best_stars||0)>=3).length,favorite,weakest,correct,wrong,attempts,accuracy:pct(correct,attempts),averageMs,highPriority:review.filter(r=>Number(r.priority||0)>=7).length,dueReview:review.filter(r=>!r.next_review_at||new Date(r.next_review_at).getTime()<=now).length};},[games,events,review]);
  const questionStats=useMemo(()=>{const map=new Map();for(const e of events){const key=e.question_type||"unknown";const row=map.get(key)||{type:key,total:0,correct:0,wrong:0,totalMs:0,timed:0};row.total++;if(e.is_correct)row.correct++;else row.wrong++;if(e.response_time_ms!=null){row.totalMs+=Number(e.response_time_ms||0);row.timed++;}map.set(key,row);}return [...map.values()].map(x=>({...x,accuracy:pct(x.correct,x.total),averageMs:x.timed?Math.round(x.totalMs/x.timed):0})).sort((a,b)=>a.accuracy-b.accuracy||b.total-a.total);},[events]);
  const weakQuestion=questionStats[0]||null;
  const wrongEvents=useMemo(()=>events.filter(e=>!e.is_correct),[events]);
  const groupedReview=useMemo(()=>{const map=new Map();for(const item of review){if(!map.has(item.surah_number))map.set(item.surah_number,[]);map.get(item.surah_number).push(item);}return [...map.entries()].sort((a,b)=>Math.max(...b[1].map(x=>x.priority))-Math.max(...a[1].map(x=>x.priority)));},[review]);
  if(user===undefined)return <div className="center"><i className="spinner"/><p>جارٍ تجهيز تقارير الألعاب...</p></div>;
  return <div className="app teacher-game-reports" dir="rtl"><main className="wrap page teacherPage">
    <section className="teacher-game-report-hero"><div><span><Icon name="game" size={18}/> تقارير الألعاب</span><h1>أثر اللعب على الحفظ والمراجعة</h1><p>النتائج هنا مبنية على جلسات اللعب الفعلية، أنواع الأسئلة، زمن الإجابة، وأخطاء الآيات المسجلة في GameEngine.</p></div><div className="teacher-game-report-art"><Icon name="chart" size={58}/></div></section>
    <section className="teacher-report-picker"><label>اختر الطالب<select value={selected} onChange={e=>setSelected(e.target.value)}><option value="">اختر طالبًا</option>{students.map(s=><option key={s.id} value={s.id}>{s.display_name} — {s.classes.join("، ")}</option>)}</select></label><button className="secondary" onClick={()=>navigate("/teacher/students")}><Icon name="users" size={17}/> الطلاب</button></section>
    {error&&<div className="msg error">{error}</div>}{loading&&<div className="center"><i className="spinner"/><p>تحميل بيانات الألعاب...</p></div>}
    {!loading&&student&&<>
      <section className="teacher-game-summary analytics"><article><span><Icon name="game" size={24}/></span><b>{summary.plays}</b><small>مرة لعب</small></article><article><span><Icon name="check" size={24}/></span><b>{summary.completions}</b><small>جولة مكتملة</small></article><article><span><Icon name="target" size={24}/></span><b>{summary.accuracy}%</b><small>دقة إجمالية</small></article><article><span><Icon name="clock" size={24}/></span><b>{summary.averageMs?`${(summary.averageMs/1000).toFixed(1)}ث`:"—"}</b><small>متوسط زمن الإجابة</small></article><article><span><Icon name="star" size={24}/></span><b>{summary.mastered}</b><small>ألعاب بإتقان 3 نجوم</small></article><article className={summary.highPriority?"attention":""}><span><Icon name="review" size={24}/></span><b>{summary.highPriority}</b><small>آيات أولوية عالية</small></article></section>
      <div className="teacher-game-insight-grid"><section className="panel"><div className="teacherSectionHead"><div><span>السلوك</span><h2>ملخص {student.display_name}</h2></div></div><div className="teacher-game-highlight"><span><Icon name="trophy" size={27}/></span><div><small>أكثر لعبة يستخدمها</small><b>{summary.favorite?gameTitle(summary.favorite.game_id):"لا توجد بيانات بعد"}</b>{summary.favorite&&<p>{summary.favorite.plays} مرة • أفضل نتيجة {summary.favorite.best_score}</p>}</div></div><div className="teacher-game-highlight warning"><span><Icon name="target" size={27}/></span><div><small>أكثر لعبة تحتاج دعمًا</small><b>{summary.weakest?gameTitle(summary.weakest.game_id):"لا توجد بيانات بعد"}</b>{summary.weakest&&<p>مؤشر الإتقان {Number(summary.weakest.mastery_score||0).toFixed(0)}%</p>}</div></div><div className="teacher-game-highlight danger"><span><Icon name="review" size={27}/></span><div><small>أضعف نوع سؤال</small><b>{weakQuestion?questionLabel(weakQuestion.type):"لا توجد محاولات كافية"}</b>{weakQuestion&&<p>{weakQuestion.accuracy}% دقة من {weakQuestion.total} محاولة</p>}</div></div></section>
      <section className="panel"><div className="teacherSectionHead"><div><span>آخر الأخطاء</span><h2>أخطاء مسجلة من الألعاب</h2></div></div>{wrongEvents.length?<div className="teacher-error-feed">{wrongEvents.slice(0,8).map((e,i)=><article key={`${e.created_at}-${i}`}><span className="history-icon"><Icon name="review" size={19}/></span><div className="grow"><b>سورة {getSurah(e.surah_number)?.name||e.surah_number} — آية {e.ayah_number}</b><small>{gameTitle(e.game_id)} • {questionLabel(e.question_type)} • {formatDate(e.created_at)}</small></div></article>)}</div>:<p className="muted">لا توجد أخطاء مسجلة بعد.</p>}</section></div>
      <section className="panel question-analytics"><div className="teacherSectionHead"><div><span>{questionStats.length} نوع سؤال</span><h2>الدقة حسب نوع السؤال</h2></div><small>{summary.dueReview} آية مستحقة للمراجعة الآن</small></div>{questionStats.length?<div className="question-stat-grid">{questionStats.map(q=><article key={q.type} className={q.accuracy<60?"weak":q.accuracy>=85?"strong":""}><div><b>{questionLabel(q.type)}</b><small>{q.total} محاولة • {q.wrong} خطأ</small></div><div className="question-meter"><span style={{width:`${q.accuracy}%`}}/></div><div className="question-stat-foot"><b>{q.accuracy}%</b><small>{q.averageMs?`${(q.averageMs/1000).toFixed(1)}ث متوسط`:"بدون توقيت"}</small></div></article>)}</div>:<p className="muted">لا توجد أسئلة مسجلة لهذا الطالب بعد.</p>}</section>
      <section className="panel teacher-games-table"><div className="teacherSectionHead"><div><span>{games.length} لعبة</span><h2>أداء الألعاب</h2></div></div>{games.length?<div className="game-report-grid">{games.map(g=>{const def=gameDefinition(g.game_id);const total=Number(g.total_correct||0)+Number(g.total_wrong||0);return <article key={g.game_id}><div className="game-report-icon"><Icon name={def?.icon||"game"} size={25}/></div><div className="grow"><h3>{gameTitle(g.game_id)}</h3><small>{def?.categoryLabel||def?.category||"لعبة"}</small><div className="game-report-metrics"><span>{g.plays} لعب</span><span>{g.completions} إكمال</span><span>{pct(g.total_correct,total)}% دقة</span><span>{g.best_score} أفضل Score</span><span>{g.best_stars}/3 نجوم</span><span>{Number(g.mastery_score||0).toFixed(0)}% إتقان</span></div></div>{def?.route&&<button className="secondary" onClick={()=>navigate(def.route)}>معاينة اللعبة</button>}</article>})}</div>:<p className="muted">لم يبدأ الطالب ألعاب GameEngine الجديدة بعد.</p>}</section>
      <section className="panel teacher-review-queue"><div className="teacherSectionHead"><div><span>Review Queue</span><h2>الآيات التي تحتاج مراجعة</h2></div><small>{review.length} آية • {summary.highPriority} عالية الأولوية</small></div>{groupedReview.length?<div className="review-queue-groups">{groupedReview.map(([surah,items])=><article key={surah}><div className="review-surah-head"><span><Icon name="quran" size={22}/></span><div><b>سورة {getSurah(surah)?.name||surah}</b><small>{items.length} آية مسجلة</small></div></div><div className="review-ayah-chips">{items.map(item=><span key={item.ayah_number} className={item.priority>=7?"high":item.priority>=4?"medium":""}>آية {item.ayah_number}<small>أخطاء {item.error_count} • أولوية {item.priority}</small></span>)}</div></article>)}</div>:<div className="teacherEmpty teacherEmptyV2"><span className="teacher-empty-icon"><Icon name="check" size={36}/></span><h3>لا توجد آيات معلقة</h3><p>عندما يخطئ الطفل في آية داخل لعبة جديدة ستظهر هنا تلقائيًا.</p></div>}</section>
    </>}
    {!loading&&!student&&<div className="teacherEmpty teacherEmptyV2"><span className="teacher-empty-icon"><Icon name="users" size={36}/></span><h3>اختر طالبًا</h3><p>اختر طالبًا مرتبطًا بأحد فصولك لعرض أثر الألعاب.</p></div>}
  </main></div>;
}
