import React,{useEffect,useMemo,useState} from "react";
import Icon from "./Icon.jsx";
import {getCurrentUser,rest,teacherOverview} from "./api.js";
import {gameDefinition} from "./gameRegistry.js";
import {getSurah} from "./surahCatalog.js";
import {AppShell,Button,Card,Empty,Hero,Metric,ProgressBar,Section,TEACHER_NAV,go} from "./ui-v4.jsx";

function gameTitle(id){return gameDefinition(id)?.title||String(id||"").replaceAll("_"," ");}
function formatDate(value){if(!value)return "—";try{return new Intl.DateTimeFormat("ar-EG",{dateStyle:"medium"}).format(new Date(value));}catch{return value;}}
function pct(value,total){return total?Math.round(Number(value||0)/Number(total)*100):0;}
function questionLabel(type){return ({next_ayah:"الآية التالية",missing_word:"الكلمة الناقصة",ayah_order:"ترتيب الآيات",word_order:"ترتيب الكلمات",chunk_order:"ترتيب أجزاء الآية",surah_name:"اسم السورة",surah_order:"ترتيب السور",ayah_number:"رقم الآية",ayah_beginning:"بداية الآية",beginning_ending:"البداية والنهاية",matching:"المطابقة"})[type]||type||"سؤال";}

export default function TeacherGameReports(){
  const [user,setUser]=useState(undefined),[students,setStudents]=useState([]),[selected,setSelected]=useState(""),[games,setGames]=useState([]),[review,setReview]=useState([]),[events,setEvents]=useState([]),[loading,setLoading]=useState(false),[error,setError]=useState("");
  useEffect(()=>{let alive=true;(async()=>{try{const current=await getCurrentUser();if(!alive)return;if(!current)return go("/login");setUser(current);const overview=await teacherOverview(current.id);if(!alive)return;setStudents(overview.students||[]);setSelected(v=>v||(overview.students?.[0]?.id||""));}catch(e){if(alive)setError(e.message||"تعذر تحميل طلاب المعلم.");}})();return()=>{alive=false;};},[]);
  useEffect(()=>{if(!selected)return;let alive=true;setLoading(true);setError("");(async()=>{try{const [gp,rq,ev]=await Promise.all([rest(`/game_progress?child_id=eq.${encodeURIComponent(selected)}&select=*&order=plays.desc`),rest(`/review_queue?child_id=eq.${encodeURIComponent(selected)}&select=*&order=priority.desc,last_error_at.desc&limit=100`),rest(`/game_ayah_events?child_id=eq.${encodeURIComponent(selected)}&select=game_id,surah_number,ayah_number,question_type,is_correct,response_time_ms,created_at&order=created_at.desc&limit=300`)]);if(alive){setGames(gp||[]);setReview(rq||[]);setEvents(ev||[]);}}catch(e){if(alive)setError(e.message||"تعذر تحميل تقارير الألعاب.");}finally{if(alive)setLoading(false);}})();return()=>{alive=false;};},[selected]);
  const student=students.find(s=>s.id===selected)||null;
  const summary=useMemo(()=>{const played=games.filter(g=>Number(g.plays||0)>0);const favorite=[...played].sort((a,b)=>Number(b.plays)-Number(a.plays))[0]||null;const weakest=[...played].sort((a,b)=>Number(a.mastery_score||0)-Number(b.mastery_score||0))[0]||null;const correct=played.reduce((s,g)=>s+Number(g.total_correct||0),0),wrong=played.reduce((s,g)=>s+Number(g.total_wrong||0),0),attempts=correct+wrong,timed=events.filter(e=>e.response_time_ms!=null);return{plays:played.reduce((s,g)=>s+Number(g.plays||0),0),completions:played.reduce((s,g)=>s+Number(g.completions||0),0),mastered:played.filter(g=>Number(g.best_stars||0)>=3).length,favorite,weakest,accuracy:pct(correct,attempts),averageMs:timed.length?Math.round(timed.reduce((s,e)=>s+Number(e.response_time_ms||0),0)/timed.length):0,highPriority:review.filter(r=>Number(r.priority||0)>=7).length};},[games,events,review]);
  const questionStats=useMemo(()=>{const map=new Map();for(const e of events){const key=e.question_type||"unknown",row=map.get(key)||{type:key,total:0,correct:0,wrong:0,totalMs:0,timed:0};row.total++;if(e.is_correct)row.correct++;else row.wrong++;if(e.response_time_ms!=null){row.totalMs+=Number(e.response_time_ms||0);row.timed++;}map.set(key,row);}return[...map.values()].map(x=>({...x,accuracy:pct(x.correct,x.total),averageMs:x.timed?Math.round(x.totalMs/x.timed):0})).sort((a,b)=>a.accuracy-b.accuracy||b.total-a.total);},[events]);
  const wrongEvents=useMemo(()=>events.filter(e=>!e.is_correct).slice(0,8),[events]);
  if(user===undefined)return <div className="center"><i className="spinner"/><p>جارٍ تجهيز تقارير الألعاب...</p></div>;
  return <AppShell mode="teacher" subtitle="تقارير الألعاب" nav={TEACHER_NAV} actions={<Button kind="secondary" icon="users" onClick={()=>go("/teacher/students")}>الطلاب</Button>} footer="أبو العزايم • تقارير اللعب مرتبطة بالسلوك الفعلي داخل الألعاب.">
    <Hero eyebrow="تقارير الألعاب" title="أثر اللعب على الحفظ والمراجعة" description="ملخص مبني على الجلسات الفعلية، الدقة، زمن الإجابة، وأخطاء الآيات المسجلة." icon="game" tone="lavender"/>
    <Section eyebrow="الطالب" title="اختار الطالب"><div className="aa-quran-toolbar"><select value={selected} onChange={e=>setSelected(e.target.value)}><option value="">اختر طالبًا</option>{students.map(s=><option key={s.id} value={s.id}>{s.display_name} — {s.classes.join("، ")}</option>)}</select><Button kind="secondary" icon="users" onClick={()=>go("/teacher/students")}>إدارة الطلاب</Button></div></Section>
    {error&&<div className="msg error">{error}</div>}{loading&&<div className="center"><i className="spinner"/><p>تحميل بيانات الألعاب...</p></div>}
    {!loading&&student&&<><div className="aa-teacher-layout"><Metric icon="game" label="مرات اللعب" value={summary.plays} tone="lavender"/><Metric icon="check" label="جولات مكتملة" value={summary.completions} tone="mint"/><Metric icon="target" label="الدقة" value={`${summary.accuracy}%`} tone="sky"/><Metric icon="star" label="ألعاب متقنة" value={summary.mastered} tone="gold"/></div>
      <Section eyebrow="السلوك" title={`ملخص ${student.display_name}`}><div className="aa-game-grid"><Card icon="trophy" title="أكثر لعبة يستخدمها" text={summary.favorite?`${gameTitle(summary.favorite.game_id)} • ${summary.favorite.plays} مرة`:"لا توجد بيانات كافية"} tone="gold"/><Card icon="target" title="أكثر لعبة تحتاج دعمًا" text={summary.weakest?`${gameTitle(summary.weakest.game_id)} • إتقان ${Number(summary.weakest.mastery_score||0).toFixed(0)}%`:"لا توجد بيانات كافية"} tone="pink"/><Card icon="review" title="آيات أولوية عالية" text={`${summary.highPriority} آية تحتاج متابعة أقرب`} tone="lavender"/></div></Section>
      <Section eyebrow={`${questionStats.length} نوع سؤال`} title="الدقة حسب نوع السؤال"><div className="aa-game-grid">{questionStats.map(q=><Card key={q.type} icon="target" title={questionLabel(q.type)} text={`${q.total} محاولة • ${q.wrong} خطأ`} tone={q.accuracy<60?"pink":q.accuracy>=85?"mint":"sky"}><div style={{marginTop:14}}><ProgressBar value={q.accuracy} label={q.averageMs?`${(q.averageMs/1000).toFixed(1)}ث متوسط الإجابة`:"الدقة"}/></div></Card>)}</div></Section>
      <Section eyebrow="آخر الأخطاء" title="آيات ظهرت فيها أخطاء">{wrongEvents.length?<div className="aa-table-list">{wrongEvents.map((e,i)=><article className="aa-table-row" key={`${e.created_at}-${i}`}><span><Icon name="review" size={20}/></span><div><b>سورة {getSurah(e.surah_number)?.name||e.surah_number} — آية {e.ayah_number}</b><small>{gameTitle(e.game_id)} • {questionLabel(e.question_type)} • {formatDate(e.created_at)}</small></div><strong>خطأ</strong></article>)}</div>:<Empty icon="check" title="لا توجد أخطاء مسجلة بعد"/>}</Section>
      <Section eyebrow={`${games.length} لعبة`} title="أداء الألعاب"><div className="aa-game-grid">{games.map(g=>{const def=gameDefinition(g.game_id),total=Number(g.total_correct||0)+Number(g.total_wrong||0);return <Card key={g.game_id} icon={def?.icon||"game"} title={gameTitle(g.game_id)} text={`${g.plays} لعب • ${g.completions} إكمال • ${pct(g.total_correct,total)}% دقة`} tone="sky" badge={`${g.best_stars||0}/3 نجوم`} action={def?.route?"معاينة اللعبة":null} onClick={def?.route?()=>go(def.route):undefined}/>})}</div></Section>
    </>}
    {!loading&&!student&&<Empty icon="users" title="اختر طالبًا" text="اختر طالبًا مرتبطًا بفصل لعرض أثر الألعاب."/>}
  </AppShell>;
}
