import React,{useMemo,useState} from "react";
import {getSurah,SURAHS} from "./surahCatalog.js";
import {selectedSurahNumber,selectSurah} from "./QuranPage.jsx";
import {Button,Card,Empty,Hero,ProgressBar,Section,go} from "./ui-v4.jsx";

const badges=[
  ["sparkle","البداية الجميلة","ابدأ أول نشاط"],["quran","أول حفظ","أكمل أول جلسة حفظ"],["star","أول سورة","أتم حفظ سورة كاملة"],["mosque","خمس سور","أتم حفظ خمس سور"],["review","مراجع صغير","أكمل أول مراجعة"],["brain","بطل الذاكرة","أكمل لعبة الذاكرة"],["puzzle","خبير الترتيب","أكمل لعبة ترتيب السور"],["bolt","نجم الاختبار","اجتز اختبار السور"],["medal","٥٠٠ نقطة","اجمع ٥٠٠ نقطة"],["trophy","أسبوع كامل","استمر ٧ أيام"]
];
function batch(total){if(total<=7)return 1;if(total<=15)return 2;if(total<=40)return 3;if(total<=100)return 5;return 7;}
function Shell({label,title,text,children}){return <div className="aa-preview-page"><Hero eyebrow={`${label} • معاينة آمنة`} title={title} description={text} icon="teacher" tone="sky"/><div className="msg ok">المعاينة لا تغيّر نقاط أو تقدم أي طالب.</div>{children}</div>;}
function Memorize(){const [number,setNumber]=useState(selectedSurahNumber()),[completed,setCompleted]=useState(0);const surah=getSurah(number)||SURAHS[0],step=batch(surah.ayahs),start=Math.min(surah.ayahs,completed+1),end=Math.min(surah.ayahs,completed+step),percent=Math.round(Math.min(completed,surah.ayahs)/surah.ayahs*100);return <Shell label="الحفظ" title={`سورة ${surah.name}`} text="اختبر شكل جلسة الحفظ من غير تسجيل بيانات."><div className="aa-learning-grid"><section className="aa-learning-card"><div className="aa-form"><label>السورة<select value={surah.number} onChange={e=>{const n=Number(e.target.value);setNumber(n);selectSurah(n);setCompleted(0);}}>{SURAHS.map(s=><option key={s.number} value={s.number}>{s.number}. {s.name} — {s.ayahs} آية</option>)}</select></label></div><div style={{marginTop:18}}><ProgressBar value={percent} label="محاكاة التقدم"/></div></section><section className="aa-learning-card"><h3>هدف الجلسة</h3><p style={{color:"var(--aa-muted)"}}>من الآية {start} إلى الآية {end}.</p>{completed<surah.ayahs?<Button className="full" onClick={()=>setCompleted(v=>Math.min(surah.ayahs,v+step))}>محاكاة إكمال الدفعة</Button>:<Button className="full" icon="review" onClick={()=>go("/review")}>معاينة المراجعة</Button>}</section></div></Shell>;}
function Review(){const [number,setNumber]=useState(selectedSurahNumber()),[score,setScore]=useState(null);const surah=getSurah(number)||SURAHS[0];return <Shell label="المراجعة" title="تجربة شاشة المراجعة" text="جرّب التقييم بدون إنشاء Review Event."><section className="aa-learning-card"><div className="aa-form"><label>السورة<select value={surah.number} onChange={e=>{const n=Number(e.target.value);setNumber(n);selectSurah(n);setScore(null);}}>{SURAHS.map(s=><option key={s.number} value={s.number}>سورة {s.name}</option>)}</select></label></div><Section title={`سورة ${surah.name}`}><div style={{display:"grid",gridTemplateColumns:"repeat(2,1fr)",gap:8}}>{[[60,"يحتاج تدريب"],[80,"جيد"],[90,"ممتاز جدًا"],[100,"ممتاز"]].map(([v,label])=><Button key={v} kind={score===v?"primary":"soft"} onClick={()=>setScore(v)}>{label} — {v}%</Button>)}</div>{score&&<div className="msg ok">نتيجة المعاينة: {score}% — لم يتم حفظها.</div>}</Section></section></Shell>;}
function Achievements(){return <Shell label="الإنجازات" title="كتالوج الميداليات" text="شاهد ما يمكن للطلاب فتحه من النشاط الحقيقي."><div className="aa-badge-grid">{badges.map(([icon,title,text])=><Card key={title} className="aa-badge" icon={icon} title={title} text={text} tone="gold" badge="معاينة"/>)}</div></Shell>;}
function Challenges(){const rows=[["quran","جلسة حفظ","دفعة حفظ يومية"],["review","جلسة مراجعة","تقييم مراجعة"],["game","لعبة تعليمية","جولة من الألعاب"]];return <Shell label="مهمات اليوم" title="كيف يرى الطفل يومه؟" text="الحالة الحقيقية تُحسب من نشاط الطفل."><div className="aa-world-grid">{rows.map(([icon,title,text])=><Card key={title} className="aa-world-card" icon={icon} title={title} text={text} tone="sky"/>)}</div></Shell>;}
export default function TeacherLearningPreview({type}){const t=useMemo(()=>type,[type]);if(t==="memorize")return <Memorize/>;if(t==="review")return <Review/>;if(t==="achievements")return <Achievements/>;if(t==="challenges")return <Challenges/>;return <Empty title="اختر قسمًا للمعاينة"/>;}
