import React,{useEffect,useRef,useState} from "react";
import Peer from "peerjs";
import {AppShell,Button,Hero,Section,go} from "./ui-v4.jsx";
function pointFromEvent(canvas,e){const rect=canvas.getBoundingClientRect();return {x:(e.clientX-rect.left)*(canvas.width/rect.width),y:(e.clientY-rect.top)*(canvas.height/rect.height)};}
function drawStroke(canvas,stroke){if(!canvas||!stroke?.points?.length)return;const ctx=canvas.getContext("2d");ctx.save();ctx.lineCap="round";ctx.lineJoin="round";ctx.lineWidth=stroke.size;ctx.globalCompositeOperation=stroke.tool==="eraser"?"destination-out":"source-over";ctx.strokeStyle=stroke.color||"#4EA8DE";ctx.beginPath();ctx.moveTo(stroke.points[0].x,stroke.points[0].y);for(const p of stroke.points.slice(1))ctx.lineTo(p.x,p.y);ctx.stroke();ctx.restore();}
export default function WhiteboardJoinPage(){
 const canvasRef=useRef(null),peerRef=useRef(null),connRef=useRef(null),drawingRef=useRef(false),strokeRef=useRef([]),pendingSnapshotRef=useRef(null);
 const [code,setCode]=useState(""),[joined,setJoined]=useState(false),[status,setStatus]=useState("أدخلي كود الجلسة الذي أرسله المعلم."),[locked,setLocked]=useState(true),[color,setColor]=useState("#4EA8DE"),[size,setSize]=useState(4),[timer,setTimer]=useState(0),[background,setBackground]=useState("paper"),[effects,setEffects]=useState([]);
 const audioRef=useRef(null);
 function drawSnapshot(data){const c=canvasRef.current;if(!data)return;if(!c){pendingSnapshotRef.current=data;return;}const img=new Image();img.onload=()=>{const ctx=c.getContext("2d");ctx.clearRect(0,0,c.width,c.height);ctx.drawImage(img,0,0);};img.src=data;}
 function sendSnapshot(){try{if(connRef.current?.open)connRef.current.send({type:"student-snapshot",canvas:canvasRef.current?.toDataURL("image/png")});}catch{}}
function playEffect(type){setEffects(v=>[...v,{id:Date.now()+Math.random(),type}]);try{const C=window.AudioContext||window.webkitAudioContext;if(!C)return;const ac=audioRef.current||new C();audioRef.current=ac;if(ac.state==="suspended")ac.resume();const now=ac.currentTime;const tone=(freq,dur,offset=0)=>{const o=ac.createOscillator(),g=ac.createGain();o.frequency.value=freq;g.gain.setValueAtTime(.0001,now+offset);g.gain.exponentialRampToValueAtTime(.035,now+offset+.01);g.gain.exponentialRampToValueAtTime(.0001,now+offset+dur);o.connect(g).connect(ac.destination);o.start(now+offset);o.stop(now+offset+dur+.02)};[523,659,784].forEach((n,i)=>tone(n,.16,i*.09));}catch{} }
 function setupCanvas(){const c=canvasRef.current;if(!c)return;const old=c.width?c.toDataURL("image/png"):pendingSnapshotRef.current;const rect=c.getBoundingClientRect(),ratio=Math.max(1,window.devicePixelRatio||1);c.width=Math.max(600,Math.floor(rect.width*ratio));c.height=Math.max(420,Math.floor(rect.height*ratio));if(old)drawSnapshot(old);pendingSnapshotRef.current=null;}
 useEffect(()=>{if(joined)setupCanvas();const fn=()=>setupCanvas();window.addEventListener("resize",fn);return()=>{window.removeEventListener("resize",fn);peerRef.current?.destroy();};},[joined]);
 function join(){const clean=code.trim().toUpperCase().replace(/[^A-Z0-9]/g,"").slice(0,5);if(clean.length!==5){setStatus("الكود يجب أن يكون 5 أحرف أو أرقام.");return;}peerRef.current?.destroy();const peer=new Peer();peerRef.current=peer;setStatus("جاري الاتصال بالمعلم…");peer.on("open",()=>{const conn=peer.connect("abu-board-"+clean,{reliable:true});connRef.current=conn;conn.on("open",()=>{setJoined(true);setStatus("تم الاتصال بالمعلم.");conn.send({type:"hello"});});conn.on("data",data=>{if(data?.type==="state"){setLocked(Boolean(data.locked));setTimer(Number(data.timer)||0);setBackground(data.background||"paper");drawSnapshot(data.canvas);}if(data?.type==="stroke"){drawStroke(canvasRef.current,data.stroke);}if(data?.type==="effect"&&data.effect)playEffect(data.effect);});conn.on("close",()=>{setJoined(false);setStatus("انقطع الاتصال بالمعلم.");});conn.on("error",()=>setStatus("تعذر الاتصال بهذه الجلسة."));});peer.on("error",()=>setStatus("لم نجد جلسة بهذا الكود. تأكدي من الكود وأن المعلم بدأ الجلسة."));}
 function start(e){if(locked)return;const c=canvasRef.current,ctx=c.getContext("2d"),p=pointFromEvent(c,e);drawingRef.current=true;strokeRef.current=[p];ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineCap="round";ctx.lineJoin="round";ctx.lineWidth=size*(window.devicePixelRatio||1);ctx.strokeStyle=color;ctx.globalCompositeOperation="source-over";c.setPointerCapture?.(e.pointerId);}
 function move(e){if(!drawingRef.current||locked)return;const c=canvasRef.current,ctx=c.getContext("2d"),p=pointFromEvent(c,e);strokeRef.current.push(p);ctx.lineTo(p.x,p.y);ctx.stroke();}
 function end(){if(!drawingRef.current)return;drawingRef.current=false;const points=strokeRef.current;strokeRef.current=[];if(points.length&&connRef.current?.open)try{connRef.current.send({type:"student-stroke",stroke:{points,tool:"pen",color,size:size*(window.devicePixelRatio||1)}})}catch{}}
 const mm=String(Math.floor(timer/60)).padStart(2,"0"),ss=String(timer%60).padStart(2,"0");
 return <AppShell subtitle="غرفة الطالب" footer="أبو العزايم • جلسة السبورة المباشرة"><div className="aa-whiteboard-page"><Hero eyebrow="السبورة المشتركة" title="انضمي إلى سبورة المعلم" description="أدخلي كود الجلسة الذي يظهر عند المعلم. ستظهر لك السبورة مباشرة، ويحدد المعلم هل يمكنك الكتابة أم المشاهدة فقط." icon="edit" tone="sky" actions={<Button kind="secondary" icon="arrow" onClick={()=>go("/")}>الرئيسية</Button>}/><Section><div className="aa-whiteboard-join-card">{!joined&&<div className="aa-join-form"><label>كود الجلسة<input autoFocus value={code} maxLength={5} onChange={e=>setCode(e.target.value.toUpperCase().replace(/[^A-Z0-9]/g,""))} placeholder="مثال: A7K2P"/></label><Button onClick={join}>دخول الجلسة</Button></div>}<div className="aa-join-status">{status}</div>{joined&&<div className={"aa-whiteboard-stage aa-bg-"+background+(locked?" is-locked":"")}>
{effects.map(effect=><div key={effect.id} className={"aa-board-effect aa-effect-"+effect.type} aria-hidden="true"><span>{effect.type==="celebrate"?"أحسنت!":effect.type==="star"?"★":effect.type==="heart"?"♥":effect.type==="trophy"?"🏆":effect.type==="clap"?"👏":""}</span></div>)}{background==="timer"&&<div className="aa-whiteboard-big-timer">{mm}:{ss}</div>}{background==="focus"&&<div className="aa-whiteboard-focus"><strong>مساحة العرض</strong><span>المعلم يعرض محتوى الدرس</span></div>}<canvas ref={canvasRef} onPointerDown={start} onPointerMove={move} onPointerUp={end} onPointerCancel={end} onPointerLeave={end}/>{locked&&<div className="aa-whiteboard-lock">المشاهدة فقط — المعلم لم يفتح الكتابة بعد</div>}</div>}</div></Section></div></AppShell>;
}