import test from "node:test";
import assert from "node:assert/strict";
import { adaptiveResumeState, challengeCountForDifficulty, createAdaptivePlan, hydrateAdaptiveChallenge, isAdaptiveResumeState, recommendDifficulty, seededShuffle, suggestNextDifficulty } from "../src/adaptiveLearning.js";

function verse(surahNumber,ayahNumber,text){return {key:`${surahNumber}:${ayahNumber}`,surahNumber,ayahNumber,text,words:text.split(" ").map((word,index)=>({text:word,position:index+1}))};}
const verses=[];for(let s=1;s<=2;s++){for(let a=1;a<=12;a++)verses.push(verse(s,a,`س${s} كلمة${a} ألف باء جيم دال هاء واو`));}
const quran={verses,surahs:[{number:1,name:"الأولى"},{number:2,name:"الثانية"}]};

test("seeded shuffle is deterministic without Math.random dependency",()=>{assert.deepEqual(seededShuffle([1,2,3,4,5],"same"),seededShuffle([1,2,3,4,5],"same"));});
test("difficulty uses age and mastery and supports manual override",()=>{assert.equal(recommendDifficulty({child:{age_years:5},progress:{completions:9,mastery_score:99}}),"easy");assert.equal(recommendDifficulty({child:{age_years:11},progress:{completions:4,mastery_score:92}}),"hard");assert.equal(recommendDifficulty({child:{age_years:9},progress:{completions:3,mastery_score:40}}),"easy");assert.equal(recommendDifficulty({child:{age_years:5},manual:"hard"}),"hard");});
test("round length stays between five and seven challenges",()=>{assert.equal(challengeCountForDifficulty("easy"),5);assert.equal(challengeCountForDifficulty("medium"),6);assert.equal(challengeCountForDifficulty("hard"),7);});
test("due review supplies forty to sixty percent of a normal plan",()=>{const reviewQueue=[2,3,4,5,6].map((ayah,index)=>({surah_number:1,ayah_number:ayah,priority:10-index,error_count:3,correct_recovery_count:0}));const plan=createAdaptivePlan({gameId:"memory-race",quran,surahNumbers:[1,2],reviewQueue,recentKeys:[],difficulty:"medium",kinds:["next_ayah","missing_word"],seed:"review-mix"});assert.equal(plan.length,6);const review=plan.filter(item=>item.source==="review_queue").length;assert.ok(review/plan.length>=0.4&&review/plan.length<=0.6,review);});
test("normal adaptive rounds do not repeat the same ayah",()=>{const plan=createAdaptivePlan({gameId:"surah-treasure",quran,surahNumbers:[1,2],reviewQueue:[],recentKeys:["1:2","1:3"],difficulty:"hard",kinds:["next_ayah","ayah_beginning","missing_word"],seed:"unique"});assert.equal(plan.length,7);assert.equal(new Set(plan.map(item=>`${item.surahNumber}:${item.ayahNumber}`)).size,plan.length);assert.ok(!plan.some(item=>["1:2","1:3"].includes(`${item.surahNumber}:${item.ayahNumber}`)));});
test("word-order challenge hydrates deterministic touch puzzle pieces",()=>{const descriptor={surahNumber:1,ayahNumber:7,kind:"word_order",source:"learning_pool",seed:"puzzle"};const first=hydrateAdaptiveChallenge(quran,descriptor,"hard");const second=hydrateAdaptiveChallenge(quran,descriptor,"hard");assert.deepEqual(first.pieces,second.pieces);assert.equal(first.answerOrder.length,first.pieces.length);});
test("resume state keeps references and validates game identity",()=>{const plan=[{surahNumber:1,ayahNumber:2,kind:"next_ayah",source:"review_queue",seed:"x"}];const state=adaptiveResumeState({gameId:"ayah-hunter",difficulty:"medium",plan,index:0,attempt:1,wrongKeys:["1:2"],startedAt:"now"});assert.equal(isAdaptiveResumeState(state,"ayah-hunter"),true);assert.equal(isAdaptiveResumeState(state,"what-next"),false);assert.equal(Object.hasOwn(state,"ayahText"),false);});
test("adaptive difficulty suggestion changes only between rounds",()=>{assert.equal(suggestNextDifficulty("medium",95),"hard");assert.equal(suggestNextDifficulty("hard",50),"medium");assert.equal(suggestNextDifficulty("easy",75),"easy");});
